$ $XConsortium: dtconfig.msg /main/3 1995/11/08 14:05:40 rswiston $
$ *****************************************************************************
$ **
$ **  File:        dtconfig.msg
$ **
$ **  Project:     CDE Session Management (dtconfig)
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtconfig
$ **
$ **  Message set 10: IBM
$ **  Message set 20: Sun
$ **
$ *****************************************************************************

$ *****************************************************************************
$ **  Message set 10: For IBM platforms
$ *****************************************************************************

$set 10
1 ⅲ逑か崼瞃囷え炟(superuser)欹⺼﹞\n
$ 
2 CDE 隃儸暋泂蠡泂囷え炟蘭郖﹞ 蘭郖\n\
ョ侇嗄譫怀纂堈囷え炟柁僳蘋渀砅鞂䬷ざ﹞\n\
衭砫⼓旂匢僛ぇ淩え﹜睎⽁禕驨鞥悒テ适隞瞅絒侇嗄﹞\n
$ 
3 杬麟⺼隃儸暋泂蠡泂囷え炟蘭郖﹞ 蘭郖\n\
ョ侇嗄譫怀纂堈囷え炟柁僳蘋渀砅鞂䬷ざ﹞\n\
衭砫⼓旂匢僛ぇ淩え﹜睎⽁禕驨鞥悒テ适隞瞅絒侇嗄﹞\n
4 CDE 儸槴暋泂蠡泂囷え炟蘭郖﹞
$ 
5 杬麟⺼儸槴暋泂蠡泂囷え炟蘭郖﹞\n
$ 
6 え恄: %s\n\
  -e (絒え dtlogin 柁 auto-start 衢逑)\n\
  -d (抻祤 dtlogin 柁 auto-start 衢逑)\n\
  -kill (裗筄 dtlogin)\n\
  -reset (适暋 dtlogin - 适隞幺抻崷殦麔)\n
$ 
7 霽ロ鰱禨 \n
$ 
8  錛衭纂堈鰱禨 \n
$ 
9  隓恄抻祤 xdm﹜霘棤櫇 xdm 轃譫葰伢郟髓抻祤\n\
xdm 呥テ箹纂﹞ \n 
$ 
10 Dtlogin 呥ゝ欹⺼ \n

$ *****************************************************************************
$ **  Message set 20: For Sun Platforms
$ *****************************************************************************

$set 20
$ 
1  CDE 崷殦襬え嶂冈
$ 
2   %s -d     (抻祤 auto-start)
3   %s -e     (絒え auto-start)
4   %s -kill  (裗筄 dtlogin)
5   %s -reset (适暋 dtlogin)
6   %s -p     (パ玿鞥棬汃彶隞)
$ 
$	In above messages 2 through 6, only translate words between
$	left "(" and right ").
$ 
7 %s: 篎 script ⽁禕髓 root 欹⺼
8 え恄: 霽ロ鰱禨
9 え恄: 錛衭纂堈鰱禨
10 藞禋⼇絫
11 隓恄欹⺼ %s
12 抻祤⼇絫
13 隓恄崽⑩ %s
14 汒 
15 痐譫磣隉侇嗄 auto-start 儸抻祤﹞
16 絒え⼇絫
17 岊攜怉 %s
18 隓恄唈ゥ %s
19 隓恄唈ゥ %s
20 痐譫磣隉侇嗄 auto-start 儸絒え﹞
21 裗筄 dtlogin 汒﹞
22 dtlogin 崷殦罶鳲儸适隞蟡蘋﹞
23 パ玿鞥棬汃彶隞儸汒
24 え恄:
