$ $XConsortium: dtcopy.msg /main/3 1996/07/24 19:02:41 drk $
$ *****************************************************************************
$ **
$ **  File:        dtcopy.msg
$ **
$ **  Project:     CDE File Manager
$ **
$ *****************************************************************************

$set 2
$ ****** Module: main_dtcopy.c ******
3 麔淰
4 麔淰
5 騵麔淰扢
6 騵麔淰扢
7 蠆諟” 隓
8 蠆諟” %d
10 え恄” %s [藞禋 ...] 坭鳲げ簅\n
11 麔淰磣隉婝 -- 麔淰扢傶棬
12 麔淰磣隉婝 -- 麔淰扢闀蕍
13 モ珜蠆諟﹜%s ゝ崽⑩﹞
14 汒﹞
15 抻祤卼
$ ** Message 20 - 32
$ ** LongFileOpNames ... message number = op + 20.
20 搢隉斕
21 瞅絒斕
22 瞅絒斕
23 瞅絒斕
24 幺抻椵廎
25 伝崽斕
26 闀蕍斕
27 唈ゥげ蠊
28 闀蕍椵廎
29 唈ゥ椵廎
30 齡汃斕
31 旂纂堈闀蕍
32 旂纂堈椵廎
33 瑀瀦

$set 3
$ ****** Module: copydialog.c ******
1 凭㶴
2 穛彘
3 傶棬斕”
4 闀蕍斕”
5 ⺍麔淰扢”
7 楙穔渿彘欐闀蕍嶂囥﹞ ズ儸闀蕍柁\n\
麔淰渿絅ョげ簅麔淰扢斕﹞
10 楙穔渿彘欐傶棬嶂囥﹞ ズ儸傶棬柁\n\
麔淰渿絅ョげ簅麔淰扢斕﹞
11 麔淰扢闀蕍 -- 滙夼
12 麔淰扢傶棬 -- 滙夼
13 抻祤闀蕍
14 凭㶴闀蕍
15 抻祤傶棬
16 凭㶴傶棬
17 儸傶棬
18 儸闀蕍

$set 4
$ ****** Module: errordialog.c ******
1 蠆諟 %s\n%s
2 モ蠆諟゛穛彘
3 麔淰扢闀蕍 -- 蠆諟
4 麔淰扢傶棬 -- 蠆諟

5 "昡ス傶棬 - 蠆諟"

6 "昡ス闀蕍 - 蠆諟"

7 "昡ス杶扜麔 - 蠆諟"

8 "攜蠢暐睎渿昡ス \n\n\
    %s\n\n\
勂蘋杶扜麔.\n\n\
Use the Change Permissions choice from the object's\n\
popup menu or from the Selected menu to turn on your\n\
Read permission on the object.\n\n\n\
Note: If this object is a folder, you must also have\n\
Read permission for each of the objects inside the\n\
folder before you can put the folder in the trash."


$set 5
$ ****** Module: overwrtdialog.c ******
1 ボ磝珜\n%s\n柁麔淰儸Бョ麔淰扢斕\n%s
2 麔淰扢傶棬 -- 麔淰适嬣
3 抻鷥Бョ柁麔淰
4 渿Бョ柁麔淰适隞杬ボ珜”
5 渿隞昡ス适隞杬ボ珜”
6 靬蝝楙堈麔淰
7 伒怮渿棬汃鶈え卼稌㶴柁ボ磝鍙秜斕﹞
8 袺粞抻柁棬汃”
9 麔淰扢闀蕍 -- 麔淰适嬣
10 %s\n儸Бョ”霘藞謥ⅱ⼃柁ボ磝﹞
11 麔淰适嬣 -- 蠆諟
12 %s\n隓恄适隞杬ボ珜\n%s\n%s

$set 6
$ ****** Module: utils.c ******
$ ** Button labels.
1 薚泂
2 穛彘
3 抻祤
4 赮伢諰咭
5 げ蠊闀蕍赮伢諰咭
6 凭㶴
7 抻祤闀蕍
8 抻祤傶棬
