$ $XConsortium: dticon.msg /main/3 1995/11/08 14:06:53 rswiston $
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dticon.msg
$ **
$ **  Project:     HP DT Icon Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dticon
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company
$ **     (c) Copyright 1993, 1994 International Business Machines Corp.
$ **     (c) Copyright 1993, 1994 Sun Microsystems, Inc.
$ **     (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
$ **         Novell, Inc.
$ **
$ **     All Rights reserved
$ **
$ **
$ *****************************************************************************
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for fileIODialog.c
$ **
$ ** messages 10-16 are for the FileSelectionBox widget (default labels)
$ *****************************************************************************

2 頝踛蹌藟蟟 -- 麔淰藣蘋/藣罐
4 頝踛蹌藟蟟 -- 麔淰藣蘋/藣罐
6 頝踛蹌藟蟟 -- 鬊Б珜
8 頝踛蹌藟蟟 -- 瞅絒麔淰
10 彶隞
12 麔淰扢
14 麔淰
16 藣蘋麔ボ”
17 藣蘋麔ボ”
18 彶隞
20 ゝ泂簅纕
22 瞅絒
24 鬊Б

$set 4
$ *****************************************************************************
$ ** _DtMessage set for newIconDialog.c
$ **
$ *****************************************************************************

2 隞頝踛髱緷涺
4 頝踛蹌藟蟟 -- 适隞彶庍騰麵
6 薚泂
8 抻祤
10 赮伢諰咭
12 隞嬥唄”
14 隞崼唄”

$set 6
$ *****************************************************************************
$ ** _DtMessage set for queryDialog.c
$ **
$ *****************************************************************************

2 頝踛蹌藟蟟 -- 滙夼
6 薚泂
$ ** DO NOT LOCALIZE - the user should never see this message
8 Do ya really wanna?
10 抻祤

$set 8
$ *****************************************************************************
$ ** _DtMessage set for stdErrDialog.c
$ **
$ *****************************************************************************

2 頝踛蹌藟蟟 -- 蠆諟
4 凭㶴

$set 10
$ *****************************************************************************
$ ** _DtMessage set for utils.c
$ **
$ *****************************************************************************

$ ** DO NOT LOCALIZE messages 2-48, they appear in the errorlog only
2 Cannot initialize button icon for circle
4 Cannot initialize button icon for solid circle
6 Cannot initialize button icon for polyline
8 Cannot initialize button icon for polygon
10 Cannot initialize button icon for solid polygon
12 Cannot initialize button icon for ellipse
14 Cannot initialize button icon for solid ellipse
16 Cannot initialize button icon for eraser
18 Cannot initialize button icon for line
20 Cannot initialize button icon for flood
22 Cannot initialize button icon for point
24 Cannot initialize button icon for rectangle
26 Cannot initialize button icon for solid rectangle
28 Cannot initialize button icon for select
30 Unable to parse static color no.
32 Unable to allocate static color no.
38 No memory(0)
40 No memory(1)
42 No memory(2)
44 No memory(3)
46 No memory(4)
48 No memory(5)

50 隓恄珫囷襲鶈え嶂冈頝踛鬊Б蟟
52 '-f' 棤禨欄隓淩囷え
54 '-i' 棤禨欄隓淩囷え
56 '-session' 棤禨欄隓淩囷え
58 隓淩柁騰麵斒眭
60 糬魦憵踛庉抻⼇絫
62 汃鞄⼇絫﹞\n⺪痝頝儸橛
64 隓淩柁謓睕棤禨

66 (ゝ杬ボ)


$set 12
$ *****************************************************************************
$ ** _DtMessage set for dtIconShell.c
$ **
$ *****************************************************************************

1 頝踛蹌藟蟟
2 灛⺪
3 頝踛蹌藟蟟 -- (ゝ杬ボ)
4 崐玾囷え頝踛蹌藟蟟﹞
6 蝫蘋骳忟
8 譖鳷⺪痝
10 棬鳷⺪痝
12 譖鳷⺪
14 虳葔
16 茯葔
18 煄磞歆憵
20 芚磞歆憵
22 藞抻
24 椴咭

$ ** message 26-198 are menu items with corresponding mnemonics
$ ** (for set grouping information, see the comment at the end-of-file)
26 N
28 覗崽(N)...
30 O
32 瞅絒(O)...
34 S
36 鬊Б(S)
38 A
40 鬊Б珜(A)...
42 x
44 廎忒(x)
46 F
48 麔淰(F)
50 U
52 艀婘(U)
54 t
56 椌抻棷棦(t)
58 C
60 赮伢棷棦(C)
62 P
64 䔝舅漜棷棦(P)
68 L
70 ⼢(L)
72 R
74 ⑶(R)
76 R
78 菕鼲棷棦(R)
82 V
84 倰枺(V)
86 H
88 纓⼳(H)
90 F
92 酈鼲棷棦(F)
94 S
96 籤坲饕棷棦(S)
98 z
100 彶庍騰麵柁頝踛(z)...
102 A
104 嚌蠹汃え鷁(A)
106 D
108 伝崽汃え鷁(D)
110 G
112 庉抻糬魦憵踛(G)
114 e
116 覗崽頝踛(e)
118 E
120 蹌藟(E)
122 V
124 ⑴侐篚鷁(V)
128 B
130 XBM(B)
134 P
136 XPM(P)
138 O
140 藣罐眭冈(O)
144 2x
146 3x
148 4x
150 5x
152 6x
154 8x
156 10x
158 12x
160 M
162 勂騰(M)
164 O
166 藞禋(O)
168 v
170 颮羏(v)...
172 T
174 齡汃(T)...
176 R
178 棤℡罶涷(R)...
180 O
182 驨卼禋げ(O)
188 U
190 囷え赮伢諰咭(U)...
192 A
194 驨卼頝踛蹌藟蟟(A)...
196 H
198 赮伢諰咭(H)

$ ** message 200-are used in the "instruction" line for current drawing mode
200 げ虳蹌藟篲冈
202 (儸蝫蘋)
204 褋嵾
206 蝫橛
208 轃蛨
210 ロ适轃
212 畈巖夆
214 ロ饡夆
216 蓛
218 蹖蓛
220 祤崽
222 藞抻
224 隓淩

$set 14
$ *****************************************************************************
$ ** _DtMessage set for help.c
$ **
$ *****************************************************************************

2 頝踛蹌藟蟟 -- 赮伢諰咭
4 睎⽁禕ョ頝踛蹌藟蟟蠡\n藞謥纂堈禋げ﹞

$set 16
$ *****************************************************************************
$ ** _DtMessage set for process.c
$ **
$ *****************************************************************************

2 ヾ麔淰隓恄Б抻\n迖讓屼隓淩柁罶涷
4 隓恄渿罶涷嬣蘋麔淰
6 楙堈笱迒泲隓恄囷え
8 隓ッ虳柁\n憵踛⑴え
10 挴泂藹隓淩柁\n嬥唄縋/迖崼唄
12 ゝ藞抻棷棦
14 隓棷棦ョッ虳揧\n椌抻迖闀蕍
16 げ虳柁頝踛泲ゝ鬊Б﹞\n\n睎惉柁彶庍鞂橝⼇﹞
20 黀栯麔淰暐⑴ḷ
22 隓恄⺌麔淰斕ャ艀瞃栠麔淰
24 隓恄渿瞃栠麔淰Б蘋麔淰斕

$ *****************************************************************************
$ ** End of _DtMessage Catalog File
$ ** (Comments only below this line)
$ *****************************************************************************
$ **
$ *****************************************************************************
$ ** Unique mnemonic groupings from set 12
$ *****************************************************************************
$ **
$ ** Unique Set 1:  (Main Menu Bar)
$ **
$ **   46 F
$ **   48 File
$ **
$ **   118 E
$ **   120 Edit
$ **
$ **   164 O
$ **   166 Options
$ **
$ **   196 H
$ **   198 Help
$ **
$ **
$ ** Unique Set 2:  (File Menu)
$ **
$ **   26 N
$ **   28 New...
$ **   30 O
$ **   32 Open...
$ **   34 S
$ **   36 Save
$ **   38 A
$ **   40 Save As...
$ **   42 x
$ **   44 Exit
$ **
$ **
$ ** Unique Set 3:  (Edit Menu)
$ **
$ **   50 U
$ **   52 Undo
$ **   54 t
$ **   56 Cut Area
$ **   58 C
$ **   60 Copy Area
$ **   62 P
$ **   64 Paste Area
$ **
$ **        Unique Set 3a:  (Rotate Sub-Menu)
$ **        68 L
$ **        70 Left
$ **        72 R
$ **        74 Right
$ **   76 R
$ **   78 Rotate Area
$ **
$ **        Unique Set 3b:  (Flip Sub-Menu)
$ **        82 V
$ **        84 Vertical
$ **        86 H
$ **        88 Horizontal
$ **   90 F
$ **   92 Flip Area
$ **   94 S
$ **   96 Scale Area
$ **   98 z
$ **   100 Resize Icon...
$ **   102 A
$ **   104 Add Hot Spot
$ **   106 D
$ **   108 Delete Hot Spot
$ **   110 G
$ **   112 Grab Screen Image
$ **   114 e
$ **   116 Clear Icon
$ **
$ **
$ ** Unique Set 4:  (Options Menu)
$ **
$ **   122 V
$ **   124 Visible Grid
$ **
$ **        Unique Set 4a:  (Output Sub-Menu)
$ **        128 B
$ **        130 XBM
$ **        134 P
$ **        136 XPM
$ **   138 O
$ **   140 Output Format
$ **   160 M
$ **   162 Magnification
$ **
$ **
$ ** Unique Set 5:  (Help Menu)
$ **
$ **   168 I
$ **   170 Introduction...
$ **   172 T
$ **   174 Tasks...
$ **   176 R
$ **   178 Reference...
$ **   180 O
$ **   182 On Item
$ **   188 U
$ **   190 Using Help...
$ **   192 V
$ **   194 Version...
$ **
