
$ "$XConsortium: dtlogin.msg /main/3 1995/11/08 14:07:17 rswiston $"

$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtlogin.msg
$ **
$ **  Project:     CDE dtlogin
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtlogin
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1990 Hewlett-Packard Company
$ **     All Rights reserved
$ **
$ **
$ *****************************************************************************
$ **
$ **
$ **  ------------------------- MODIFICATION RECORD --------------------------
$ *
$ * 
$ **  ----------------------- MODIFICATION RECORD END ------------------------
$ *****************************************************************************
$ *************************************<+>*************************************

$ *************************************<L>*************************************
$ **  -----------------GENERAL LOCALIZATION NOTES SECTION---------------------
$ * Comment lines begin with a $ except $set which indicates the start of a 
$ * new set.
$ *
$ * Do not delete any comments; you may add comments for your use.
$ *
$ **  ----------------GENERAL LOCALIZATION NOTES SECTION END------------------
$ *************************************<L>*************************************

$set 1
$ set 1 is labels
$ 
$ messages 1 through 6 are button labels on the login screen

1 霘藣蘋睎柁囷え炟ボ磝
2 霘藣蘋睎柁湅謑
3 薚泂
4 适隞瞅沓
5 藞禋
6 赮伢諰咭

$ 
$ messages 7 through 11 are options button menu items
$ 

7 适暋僳蘋糬魦
8 杬麟⺼僳蘋
9 斿ヾ...
10 痼槉嵺瞃栠汃鞄
11 諴侔

$ 
$ messages 12 through 14 are miscellaneous button labels
$ 
12 瞅沓 DT
13 抻祤 
14 赮伢諰咭


$ 
$ message 15, 17 are more option button menu items 
$ message 16 is the welcome message
$ 
15 DT Lite 瞃栠汃鞄
16 崐玾囷え
17 纂郫痐譫磣隉侇嗄

$ 
$ message 18-24
$ 
18 * 穛彘痐譫磣隉侇嗄僳蘋...\r\n*\r\n
19 * ヵ錛僳蘋菙ざ﹜霘挹 [Enter]﹞\r\n*\r\n
20 * 僳蘋﹞ョ睎僳罐欄悒攜躁﹜痐譫磣隉侇嗄僳蘋伒渿凭㶴﹞\r\n*\r\n
21 * 痐譫磣隉侇嗄僳蘋凭㶴斕...\r\n*\r\n
22 * ョ䬷ざ蟟 %1$s 譫絒棬痐譫磣隉侇嗄僳蘋...\r\n*\r\n
23 * 霘ッ嶉恁痐譫磣隉侇嗄僳蘋糬魦罐隃欄悒テ⺼僳蘋﹞\r\n*\r\n
24 * %1$s 䬷ざ蟟譫隓恄絒棬 X ɵ峇蟟...\r\n*\r\n

$ messages 25 is a options button menu item
25 瞃栠汃鞄

$ 
$ 26 replaces 16 as the greeting after a user name has been 
$ entered. The %s is replaced by the user name.
$ 
26 崐玾 %s

$ 
$  Sun specific message catalog id numbers in MC_LABEL_SET messages.
$  (Starting at a random uneven higher number, 73, to allow some room
$  for some shared sample source message additions.
$ 
73 囷え炟譫纂痐譫磣隉侇嗄

$set 2
$ set 2 is error messages
$ 

1 僳蘋攜薚﹜霘テ箹纂﹞
2 隓恄䨣葎怉媊沓げ蠊﹞
3 侺暽﹞げ虳僳蘋柁囷え炟藺禨儸蝞頖迻﹞
$ message 4 is a lengthy message that should be localized to correspond to 
$ the language.  
4 \n\
睎⽁禕藞謥纂堈媊沓湅謑﹜\n\
迖炟旂睎柁隃⺼湅謑儸蝝蛺﹞\n\
\n\
暋泂ン湅謑欄悒﹜霘囷え隞湅謑\n\
适隞僳蘋纂﹞
5 僳蘋蠆諟﹜囷え炟 id 隓淩﹞
6 僳蘋蠆諟﹜漦嗢 id 隓淩﹞
7 僳蘋蠆諟﹜謒淭  id 隓淩﹞
8 僳蘋蠆諟﹜謒淭憿簅隓淩﹞
9 げ虳僳蘋衢逑揧抻祤﹞
10 ⅲ淂囷え炟⑴欹⺼ %1$s\n
11 皕 %1$s 适隞唈擛蠡泂柁諴侔覗痼\n
12 适隞筈萺崷殦麔縋ɵ峇蟟麔\n
13 适隞幺抻崷殦麔 %1$s\n
14 适隞幺抻ɵ峇蟟麔 %1$s\n
15 适隞幺抻Б抻麔 %1$s\n
16 dtlogin”琣冈跂潞奡襉忟\n


$set 3
$ set 3 is help text
$ 

$ message 1 is generated when the help button on the login screen is clicked.
1 \n\
僳蘋赮伢諰咭”\n\
\n\
霘囷え僳蘋鳪郖⣷諔瑼洁蝚睎柁冼ソ﹞\n\
\n\
蚍衭僳蘋”\n\
       1) 耰蘋睎柁囷え炟ボ磝﹜隑悒挹 <Enter> 耰迖挹纂譯 [薚泂]﹞\n\
          (ヵ峈睎泲ゝ唈ゥ纂堈囷え炟﹜霘藣蘋 "root" 惉珜\n\
	  囷え炟ボ磝\n\
       2) 耰蘋睎柁湅謑﹜隑悒挹 <Enter> 耰迖挹纂譯 [薚泂]﹞\n\
\n\
[适隞瞅沓]\n\
   祤崽睎柁藣蘋禋﹜髓砅适隞藣蘋睎柁囷え炟ボ磝\n\
   适箹纂﹞\n\
\n\
[藞禋]\n\
   逑⣷睎䨣彶瞃栠汃鞄藞禋”\n\
\n\
   渿僶趡挴簅殦卼 [藞禋] 挹瘖欄譫﹜挹⻖ \n\
   僶趡挹瘖 1﹞侹挴簅汃藞謥﹞\n\
   撋挴簅⻏卼栲堈禋げ譫巖﹜勂瞅\n\
   僶趡挹瘖伒⑴藞抻篎禋げ﹞睎⑴髓藞謥”\n\
\n\
   諴侔 - 庍䨣瞃栠汃鞄囷え柁諴侔\n\
   瞃栠汃鞄 - 藞謥纂堈頝夆蘄頨\n\
     OpenWindows 痐譫磣隉侇嗄 - 珜 OW 痐譫磣隉侇嗄 \n\
     纂郫痐譫磣隉侇嗄 - 珜纂郫痐譫磣隉侇嗄蘄頨 (CDE) \n\
     囷え炟譫纂痐譫磣隉侇嗄 - 珜譫纂僳蘋 \n\
     捗錏⺌棬砉覈瞃栠汃鞄 - 珜痼纂 X 槉嵺蘄頨\n\
   杬麟⺼僳蘋 - 鼲葎杬麟⺼蘄頨\n\
   适暋僳蘋糬魦 - 适隞絒棬 X ɵ峇蟟\n\
\n\
囷えズ纂僶趡挹瘖ョ茯葔ズ纂搢挹纂譯﹜伒⑴\n\
怑隞糬魦﹞睎⑴髓ョ侇嗄媢桾う鶳怉糬魦髓茬\n\
卼攜晥厙櫇幺渀﹜囷え衢逑﹞\n\
\n\
ヵ錛彶ロ柁赮伢諰咭罶媢﹜霘僳蘋悒ョ虳巖郖帣柁\n\
＞赮伢諰咭磣隉炟＝頝踛 (淝譫纂堈棯磍炟) 譫挹\n\
纂譯﹜伒⑴岊怉＞僳蘋磣隉炟＝赮伢諰咭咇纂癱﹞\n\

$ message 2 is generated when you attempt to start a system whose id is
$ set to unknown or if it is not configured for networking.
2 \n\
睎柁齡汃袘ボ磝縋怬鱗齡汃袘适闀﹞モげ虳揧暋泂\n\
＞unknown＝﹞唈諞睎蜌楙堈齡汃袘テ杬ボ纂﹞\n\
\n\

$ message 3 is generated when the help button on the chooser screen is clicked.
3 \n\
藞謥嶂冈赮伢諰咭”\n\
\n\
霘囷え藞謥嶂冈糬魦藞謥衭僳蘋柁ɵ峇蟟﹞\n\
\n\
藞謥嶂冈糬魦屼纂堈ト玿﹜怀堈禋げ楁讓挭怚堈\n\
楶禳﹞剼纂堈楶禳 (ɵ峇蟟ボ磝) 屼怀纂堈⑴えɵ\n\
峇蟟柁篚聤ボ磝﹞剼蘑堈楶禳 (ɵ峇蟟罶媢)\n\
衧呣怀堈ɵ峇蟟譫欹⺼柁僳蘋磣隉炟攜フ﹜\n\
゛攜フ柁罶媢﹞ヵ峈栲堈ɵ峇蟟欹⺼\n\
CDE 痐譫磣隉侇嗄﹜楶ソ祼鞂菙坯げ虳\n\
ョ囷え侇嗄柁囷え炟 (迖 tty 稹殦) 柁藺禨﹜\n\
髓轡虳 5﹝10﹝15 禳㺪柁衿蟡⼳忔圊 (CPU ⼳忔囷え畽)\n\
嶉罶媢﹞\n\
\n\
衭藞謥纂堈ɵ峇蟟僳蘋﹜ⅲ衭ョトざ斕藞抻\n\
睎裱僳蘋柁ɵ峇蟟ボ磝柁咇纂⺼伒⑴﹞\n\
\n\
汃ン藞謥欄悒﹜霘挹＞薚泂＝挹瘖﹞糬魦譫祼鞂\n\
罐隃睎邴藞謥柁ɵ峇蟟柁僳蘋糬魦﹞\n\
\n\
[彶隞トざ]\n\
   楙堈藞禋鞂覗崽トざ﹜呥栯緧篚聤譫柁ɵ峇\n\
   蟟﹜砫旂匢蠢暐僳蘋悒﹜适隞唈擛トざ﹞\n\
\n\
[藞禋]\n\
   ⣷睎䨣彶瞃栠汃鞄藞禋”\n\
\n\
   渿僶趡挴簅殦卼 [藞禋] 挹瘖欄譫﹜挹⻖ \n\
   僶趡挹瘖 1﹞侹挴簅汃藞謥﹞\n\
   撋挴簅⻏卼栲堈禋げ譫巖﹜勂瞅\n\
   僶趡挹瘖伒⑴藞抻篎禋げ﹞睎⑴髓藞謥”\n\
\n\
   諴侔 - 庍䨣瞃栠汃鞄囷え柁諴侔\n\
   适暋僳蘋糬魦 - 适隞絒棬 X ɵ峇蟟\n\
\n\
囷えズ纂僶趡挹瘖ョ茯葔ズ纂搢挹纂譯﹜伒⑴\n\
怑隞糬魦﹞睎⑴髓ョ侇嗄媢桾囂鶳怉糬魦髓茬\n\
卼攜晥厙櫇幺渀﹜囷え衢逑﹞\n\
\n\


$set 4
$ set 4 is log error messages
$ 

1 Б抻麔淰 "%1$s"﹜饜鞥 "%2$s" 隓恄岊怉\n
2 ReadHostEntry\n
3 Б抻麔淰 %1$2s﹜䬷ざ蟟 %1$2s 珜攜咭柁䬷ざ蟟\n
4 隓恄瞅絒Б抻祰戔麔 %1$s﹜モ隓恄嵹鶈 XDMCP 衭忴\n
5 篚棦/謦汃侇嗄薚諝蠆諟”%1$s (%2$s/%3$s)
6 隓恄瞅絒ɵ峇蟟薚諝麔 %1$s\n
7 隓恄嬣蘋ɵ峇蟟薚諝麔 %1$s\n
8 saveAddr
9 蘀抻篚聤蘭郖崷殦渀棯纕
10 setAuthNumber
11 隓恄孍泂筅ḷ麔 %1$s 迖猻ソ麔 %2$s\n
12 隓恄渿筅ḷ麔傶怉懱撋⻏殦\n
13 隓恄唈ゥ/孍泂 pid 麔淰 %1$s\n
14 隓恄孍泂 pid 麔淰 %1$s﹜モ珜ⅱ纂堈 Dtlogin ョ欹⺼ (pid %2$d)\n
15 隓恄Б抻ɵ峇蟟麔淰 %1$s\n
16 NewDisplay
17 隓恄瞅絒 errorLogFile %1$s\n
18 TrimErrorLog()”蠆諟戀諲麔柁麔淰騰麵迻戔瑊騰珜 200Kb﹞\n
19 ɵ峇蟟麔淰谹韁䬷ざ蟟ボ磝\n
20 %1$s 谹韁䬷ざ蟟麷倛\n
21 饜鞥ボ磝 %1$s 隓淩﹞DISPLAY 暋泂珜 ':0'\n
22 䬷ざ蟟 %2$s 柁䬷ざ蟟麷倛 %1$s 隓恄揧稌抰\n
23 摫鶅适暋蝺渀﹞\n
24 GetResource
25 扽洠睮⑴坯鰱禨适隞崷殦\n
26 隓恄瞅絒崷殦麔 %1$s\n
27 杬麟⺼ロ瀦柁鰱禨”
28 StartServer()”扽鰱禨\n
29 ɵ峇蟟 %1$s 隓恄欹⺼\n
30 StartServer() 雰ぇ騵嶂囥⼇絫﹜穛彘斕\n
31 ɵ峇蟟蜑⼃斕黫\n
32 XOpenDisplay(%1$s) 閰箹 #%2$d 斕欐﹜ョ斕黫﹞\n
33 瞅絒ɵ峇蟟閰箹 #%1$d ⼇絫﹜モ珜 %2$s﹜勂蛫テ閰箹\n
34 ╩适 IO 蠆諟 %d (%1$s)\n
35 X 蠆諟\n
36 瞃栠汃鞄絒沓蠆諟\n
37 滙夼”䬷ざ蟟 %1$s 隓恄砉錏Еツ\n
38 滙夼”䬷ざ蟟 %1$s 柁耰薏隓恄砉錏Еツ\n
39 BLS - 隓恄蘀痤鷓韝罶媢﹞\n
40 BLS - 隓恄蘀痤抰砉៻柁鷓韝罶媢﹞\n
41 BLS - 隓恄无糶絔裧嶂唄﹞\n
42 BLS - 隓恄䨣彶珜囷え炟”%1$s﹞\n
43 AFS - 絒棬瞃栠汃鞄渀 setgroups() ⼇絫\n
44 囷え炟 %s Setuid ⼇絫﹜errno = %d\n
45 囷え炟 %2$s 扽絒沓げ蠊 %1$s﹜囷え /\n
46 瞃栠汃鞄欹⺼⼇絫 %1$s\n
47 瞃栠汃鞄扽杬麟/鰱禨\n
48 隓恄絒棬 %s 柁瞃栠汃鞄﹜雰ぇ騵嶂囥⼇絫\n
49 Dtlogin 隓恄覗崽剟鷓鞥\n
50 隓恄欹⺼ %1$s\n
51 隓恄雰ぇ騵嶂囥髓欹⺼ %1$s\n
52 攜懱撋柁薚諝ボ磝 "%1$s"﹞囷え AFS﹝Kerberos 迖蠡泂ボ磝﹞\n
53 %2$s 隓恄欹⺼ Dtgreet %1$s \n
54 隓恄雰ぇ騵嶂囥髓欹⺼ Dtgreet %1$s\n
55 %1$d 棔唈ゥ葅桵⼇絫\n
56 廎ポ葅桵⻏彴 %1$d 蠆諟﹜errno = %2$d\n
57 makeEnv
58 setEnv
59 parseArgs
60 %1$s げ蠊柁筈萺渀睮熅蝝 %2$d 秮﹞廎忒筈萺斕...\n
61 %s 㪫卼 %1$d 堈髓譫柁漦嗢﹜%2$s 鞂揧芩靬\n
62 audwrite() 蠆諟”昋ⅰ炟呥盻崼瞃囷え炟\n
63 audwrite() 蠆諟”謒淭奡蠊斕隓淩柁呦ス磍謑﹞\n
64 audwrite() 蠆諟”errno = %1$d\n
65 AFS 薚諝⼇絫”%1$s\n
66 %1$s 柁鷓韝儸怉蛺﹞霘縋睎柁侇嗄磣隉婝椵彄﹞\n
67 ɵ峇蟟斕欐  %1$s\n
68 隓恄瞅絒簅諲⻏蠣旃晛麔”%1$s\n
69 隓恄幺抻 "%1$s" 媢桾げ蠊﹞囷え蠡泂諴侔﹞
70 䬷ざ蟟 %1$s 隓恄絒沓暋泂﹜ɵ峇蟟⑴逑揧庉抻﹞\n
71 (%1$s)”僳蘋 matte 嬥唄熅蝝䬷ざ蟟嬥唄﹜囷え蠡泂圊﹞matte 柁痼⻏珜頝踛痼蠣﹞\n
72 (%1$s) 僳蘋 matte 崼唄熅蝝䬷ざ蟟崼唄﹜囷え蠡泂圊﹞matte 柁痼⻏珜頝踛痼蠣﹞\n

$set 5
$ set 5 is for other stuff specific to chooser.
1 霘藞謥纂堈ɵ峇蟟僳蘋”
$ 1 is the title/instructions for the chooser dialog
2 ɵ峇蟟ボ磝                    ɵ峇蟟罶媢
$                                ^
$                                | This needs to start in this column
$ 2 is the headings for the list
3  彶隞トざ 

$set 99
$    DO NOT TRANSLATE THESE MESSAGES
$    DO NOT CHANGE THESE MESSAGES
$    DO NOT LOCALIZE THESE MESSAGES
$    These messages are used for the version information.
$quote "
1 "@(#)version_goes_here"
2 "\n@(#)_DtMessage catalog source $XConsortium: dtlogin.msg /main/3 1995/11/08 14:07:17 rswiston $"

