$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/4 1998/05/22 17:08:11 rafi $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "薚泂"
$ 	    /* NL_COMMENT
$ 	     * This is a menu label, please refer to the resource file "Dtmail" for
$            * appropriate mnemonics tranlation
$ 	     */
2 "瑧ス藞禋..."
3 "⺌棬ャ砆"
4 "笱迒彶隞斕..."


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "抻祤"
6 "諔騵瑧ス"
7 "諔騵瑧ス"
8 "諔騵瑧ス"
9 "伝崽"
10 "譯纂堈"
11 "虳纂堈"
12 "ャ鷋溈ス藺"
13 "トパ"
14 "婽ス藺"
15 "饜纕"
16 "戀蛺昑渀睮"
17 "騰麵"
$ 	    /* NL_COMMENT
$            * Menu labels in Main Mailer (from RoamMenuWindow.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 18-22,25,28,29 are menu labels for "Mailbox" pull down menu.
$            * Message 30,31,33-40 are menu labels for "Message" pull down menu. 
$            * Message 43-45 are menu labels for "Edit" pull down menu. 
$            * Message 47--55 are menu labels for "View" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
18 "瑧謜"
19 "黀栯旂匢隞瑧ス"
20 "瞅絒ス謜"
21 "瞅絒ス謜"
22 "隞瑧ス..."
23 "諔騵瑧ス - 隞瑧ス"
24 "隞瑧ス"
25 "瞅絒..."
26 "諔騵瑧ス - 瞅絒"
27 "瞅絒"
28 "曚骱儸伝崽柁媢桾"
29 "驨椲"
30 "瞅絒"
31 "鬊Б珜齪А麔..."
32 "諔騵瑧ス - 媢桾 - 鬊Б珜齪А麔"
33 "闀蕍怉"
34 "トパ..."
35 "硻岊..."
36 "ツ楶藞抻"
37 "伝崽"
38 "抻祤伝崽虳纂堈媢桾"
39 "皕ト玿斕抻祤伝崽..."
40 "媢桾"
41 "傶棬"
42 "諔騵瑧ス - 媢桾"
43 "闀蕍"
44 "ツ楶藞抻"
45 "蹌藟"
46 "諔騵瑧ス - 齪А"
47 "譯纂堈"
48 "虳纂堈"
49 "玿韝醷嬣"
50 "呣戀蛺/渀睮粡囥"
51 "呣婽ス藺粡囥"
52 "呣饜纕粡囥"
53 "呣騰麵粡囥"
54 "呣昲鳷粡囥"
55 "髲砫"
56 "隞媢桾"
57 "隞媢桾﹜屼挭ツ楶"
58 "鼲婽媢桾"
59 "ャ鷋婽ス藺"
60 "ャ鷋邴藺"
61 "ャ鷋婽ス藺﹜屼挭"
62 "ャ鷋邴藺﹜屼挭"
63 "ャ砆"
64 "傶棬"
65 "怬鱗瑧謜..."
66 "ⅱБ隞麔..."
67 "諔騵瑧ス - 眃㪫稹殦 - ⅱБ隞麔"
68 "ツ楶藞抻"
69 "眃㪫稹殦"
70 "諔騵瑧ス - 眃㪫稹殦"
71 "颮羏"
72 "齡汃"
73 "棤嘵"
74 "驨卼禋げ"
75 "囷え赮伢諰咭"
76 "赮伢諰咭"
77 "驨卼諔騵瑧ス..."
78 "諔騵瑧ス攜覗鞁瑧謜柁昲鳷﹞\n霘藞謥＞薚泂＝驨椲瑧謜悒﹜テ适隞絒棬諔騵瑧ス﹞"
79 "鼲葎斕... 汒 %d %%"
80 "諔騵瑧ス"

$ 
$ Strings from dtmail/AttachArea.C

81 "諔騵瑧ス"
82 "諔騵瑧ス"
83 "諔騵瑧ス"


$ 
$ Strings from dtmail/Attachment.C

84 "%s 旂纂堈⑴欹⺼柁眃㪫稹殦﹞  睎裱欹⺼蓇?"
85 "諔騵瑧ス"
86 "諔騵瑧ス"
87 "諔騵瑧ス"
88 "諔騵瑧ス"


$ 
$ Strings from dtmail/RoamCmds.C

89 "諔騵瑧ス - 怬鱗瑧謜"
90 "傶棬"
91 "トパ..."
92 "薚泂"
93 "鬊Б"
94 "鬊Б"
95 "鬊Б"
96 "覗洠"
97 "庍ボ"
98 "諔騵瑧ス - 庍ボ"
99 "諔騵瑧ス"
100 "薚泂"
101 "抻祤"
102 "睎儸ョ⺌棬ャ砆髓⼃柁藞禋斕\n囷え藹鼲婽鞥逑﹞  ⺌棬ャ砆欹⺼渀 \n﹜⺌棬ャ砆鞂眃蠹怉篎藞禋\n柁鼲婽汃鞄斕﹞  睎薚泂衭絒棬⺌棬ャ砆蓇?\0"
103 "諔騵瑧ス"
104 "睎ョ .forward 麔淰斕儸欹⺼⺌棬ャ砆嶂冈﹞\n霘皕諰咭齪ス斕栯罐ヵ彘欐嶂冈﹜呥渿⼓皕 .forward 麔淰斕伝崽﹞\n棯纕箾扻悒﹜霘テ箹纂挴麟﹞\0"
105 "隓恄瞅絒 .vacation.msg 麔淰 -- 扽嬣蘋暐⑴ḷ﹞"
106 ".vacation.msg 麔淰儸Бョ﹞  衭髓隞齪А抻鷥蓇?"
107 "隓恄瞅絒 .vacation.msg 麔淰 -- 扽嬣蘋暐⑴ḷ﹞"
108 "宎ョザ徦撋斕"
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "宎ョザ徦撋斕﹞\n嶉宎ャ坭悒﹜鞂櫇幺睎婽坭驨 \"$SUBJECT\" 柁瑧ス﹞\n"


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N"


$ 
$ Strings from dtmail/Undelete.C

115 "抻祤伝崽"
116 "驨椲"

$ 
$ Strings from dtmail/SendMsgDialog.C

$ 	    /* NL_COMMENT
$            * Menu labels in Compose dialog (from SendMsgDialog.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 117,121,122,125,127-129 are menu labels for "File" pull down menu.
$            * Message 130-134,139,140,155,156 are menu labels for "Edit" pull down menu. 
$            * Message 141,142,145,147-150,226 are menu labels for "Attachment" pull down menu. 
$            * Message 152-154,157 are menu labels for "Format" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
117 "婽罐"
118 "驨椲"
119 "隞媢桾"
120 "諔騵瑧ス"
121 "麔淰"
122 "屼挭..."
123 "諔騵瑧ス - 屼挭"
124 "屼挭"
125 "鬊Б珜齪А麔..."
126 "諔騵瑧ス - 鬊Б珜齪А麔"
127 "戀諲媢桾"
128 "汃珜...婽罐"
129 "驨椲"
130 "蹌藟"
131 "籔婘"
132 "椌抻"
133 "闀蕍"
134 "鶼漜"
135 "笱眻鶼漜"
136 "蠹巖挭芧"
137 "醷粡"
138 "覗崽"
139 "伝崽"
140 "ツ楶藞抻"
141 "眃㪫稹殦"
142 "嚌蠹麔淰..."
143 "諔騵瑧ス - 嚌蠹"
144 "嚌蠹"
145 "ⅱБ隞麔..."
146 "諔騵瑧ス - 眃㪫稹殦 - ⅱБ隞麔"
147 "伝崽"
148 "抻祤伝崽"
149 "庍ボ"
150 "ツ楶藞抻"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "䬷ざ嵺眭"
152 "眭冈"
153 "⺌棬葎⺼"
154 "暋泂圊..."
155 "硻岊/彶庍..."
156 "捋А黀栯..."
157 "篲帣"
158 "諔騵瑧ス - 眃㪫稹殦"
159 "諔騵瑧ス - ャ砆"
160 "隞媢桾"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "闀蕍"
162 "ツ楶藞抻"
163 "蹌藟"
164 "ⅱБ隞麔..."
165 "諔騵瑧ス - 眃㪫稹殦 - ⅱБ隞麔"
166 "ツ楶藞抻"
167 "眃㪫稹殦"
168 "諔騵瑧ス - 眃㪫稹殦"
169 "諔騵瑧ス - 齪А"
170 "颮羏"
171 "齡汃"
172 "棤嘵"
173 "驨卼禋げ"
174 "囷え赮伢諰咭"
175 "赮伢諰咭"
176 "驨卼諔騵瑧ス..."
177 "諔騵瑧ス"


$ 
$ Strings from dtmail/DtMailGenDialog.C

$  /* NL_COMMENT
$   * 178 and 179 are obsolete messages, replaced by messages
178 "諔騵瑧ス - 驨卼 Dtmail"
179 "Dtmail Version 1.0"
180 "薚泂"
181 "薚泂"
182 "抻祤"

$ 
$ Strings from dtmail/FindDialog.C

183 "硻岊"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "硻岊呥藞抻ツ楶"
185 "覗崽"
186 "驨椲"
187 "赮伢諰咭"
188 "ス藺”"
189 "溈ス藺”"
190 "饜纕”"
191 "棓ヾ”"
192 "諔騵瑧ス - 硻岊"
193 "芼譯硻岊"
194 "芼ャ硻岊"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */


$ 
$ Strings from dtmail/Editor.C

195 "------------- Begin Forwarded Message -------------\n\n" 
196 "------------- Begin Included Message -------------\n\n" 
197 "------------- End Forwarded Message -------------\n\n" 
198 "------------- End Included Message -------------\n\n" 

$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n------------- Begin Included Message -------------\n" 
200 "\n------------- End Included Message -------------\n" 

$ 
$ Strings from dtmail/DtEditor.C

201 "\n------------- Begin Included Message -------------\n" 
202 "\n------------- End Included Message -------------\n" 

$ 
$ Strings from dtmail/Editor.C
$ 195 "------------- 鼲婽媢桾瞅沓 -------------\n\n"
$ 196 "------------- 屼挭媢桾瞅沓 -------------\n\n"
$ 197 "------------- 鼲婽媢桾廎忒 -------------\n\n"
$ 198 "------------- 屼挭媢桾廎忒 -------------\n\n"
$ 
$ Strings from dtmail/XmTextEditor.C
$ 199 "\n------------- 屼挭媢桾瞅沓 -------------\n"
$ 200 "\n------------- 屼挭媢桾廎忒 -------------\n"
$ 
$ Strings from dtmail/DtEditor.C
$ 201 "\n------------- 屼挭媢桾瞅沓 -------------\n"
$ 202 "\n------------- 屼挭媢桾廎忒 -------------\n"

$ 
$ Strings from dtmail/ComposeCmds.C

203 "諔騵瑧ス"
204 "隓恄唈ゥャ砆槉嵺﹞"
205 "諔騵瑧ス"
206 "隓恄唈ゥャ砆槉嵺﹞"
207 "諔騵瑧ス"
208 "隓恄唈ゥャ砆槉嵺﹞"
209 "諔騵瑧ス"
210 "隓恄唈ゥャ砆槉嵺﹞"
211 "諔騵瑧ス"
212 "篲帣攜Бョ﹞"
213 "諔騵瑧ス"
214 "篲帣ʊ驗儸銧骱﹞"
215 "諔騵瑧ス"
216 "奡襉忟攜冞﹜隓恄蟡蘋篲帣﹞"
217 "諔騵瑧ス"
218 "篲帣ʊ驗儸銧骱﹞"

$ 
$ Strings from dtmail/SortCmd.C

219 "粡囥斕..."

220 "ツ楶藞抻"
221 "ス謜"

222 "%a %b %d %k”%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%a %b %d %H”%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%a %b %d %k”%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%a %b %d %H”%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "䬷ざト玿"

$ String from Undelete.C, Deleted Messages window title
227 "諔騵瑧ス - Deleted Messages"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "嚌蠹"
229 "伝崽"
230 "蒡婽"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "銌硻..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "藞泂 1 媢桾"
233 "藞泂 %d 媢桾"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "岊攜怉砨嗃媢桾"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "諔騵瑧ス - 驨卼諔騵瑧ス"
236 "諔騵瑧ス 1.0 斿ヾ"

$set 2
1 "諔騵瑧ス"
2 "ToolTalk 泲ゝ瑱⺼媊沓暋泂﹞  諔騵瑧ス隓恄ョ扽 ToolTalk 柁硠扃譯欹⺼﹞\n霘閰箹絒棬 /usr/dt/bin/dtsession﹜迖鏺彄睎柁侇嗄磣隉婝﹞"

3 "槉嵺隓恄瑱⺼媊沓暋泂﹞  廎忒斕﹞\n"
4 "諔騵瑧スЕ稹棯纕﹜\n\モ欹⺼漦嗢暋泂蠆諟﹜\n\邴髓隓恄欹⺼"
5 "睎攜怞暐⑴ḷ﹜隓恄髲砫 %s"
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "瑧謜 %s 旂纂堈げ蠊﹜隓恄瞅絒﹞"
7 "隓恄渿 %s 覗洠﹞  モ珜⼓攜Бョ﹞"
8 "鬊Б棷 %s 儸覗洠﹞"
9 "蠆諟 - 隓恄覗洠 %s"
10 "諔騵瑧ス"
11 "%s"
12 "諔騵瑧ス"
13 "諔騵瑧ス"
14 "眃㪫稹殦⽁禕ッ藞抻﹜懼逑欹⺼＞ⅱБ隞麔\＝挴麟渿⼓Б怉纂堈\n\麔淰蠡﹞"

15 "蠆諟 - 隓恄抻痤 mailrc﹞"
16 "泲ゝ藞抻媢桾﹞"
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */


17 "睎儸蹌藟蝝 \"%s\"﹜羼鰹衭伝崽蓇?"
18 "蠆諟”隓恄屼挭麔淰 %s"
19 "眃㪫稹殦⽁禕ッ藞抻﹜懼逑欹⺼＞ⅱБ隞麔＝挴麟渿⼓Б怉纂堈\n\麔淰蠡﹞"


20 "眃㪫稹殦⽁禕ッ藞抻﹜懼逑欹⺼＞ⅱБ隞麔＝挴麟渿⼓Б怉纂堈\n\麔淰蠡﹞"

21 "諔騵瑧ス"



$set 3
1 "⺌棬鬊Б斕..."

2 "媊沓暋泂斕..."
3 "瑧謜 %s 攜Бョ﹞\n\睎裱唈ゥ楙堈ボ磝柁瑧謜蓇?"
4 "諔騵瑧ス"
5 "薚泂"
6 "瑧謜 %s 揧孍泂﹞\n\睎⑴髓え鷗棬柁巖冈箾崽孍泂﹜隑悒テ箹纂“\n\迖旂鏺彄睎柁侇嗄磣隉婝﹞"
7 "諔騵瑧ス"
8 "薚泂"
9 "薚泂"
10 "薚泂"
11 "薚泂"
12 "%s"
13 "媢桾 %d (ヅ %d 衧媢桾)﹜%d 衧隞媢桾﹜%d 衧儸伝崽"
14 "媢桾 %d (ヅ %d 衧媢桾)﹜%d 衧隞媢桾﹜%d 衧儸伝崽"
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "鬊Б斕..."
16 "諔騵瑧ス"
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
$		/* NL_COMMENT
$		 * Messages 16 and 17 are no longer being used.  They are
$		 * being replaced by messages 86 and 87.
$		 */
17 "衭皕楙堈瑧謜斕曚骱睎簅ざ衭伝崽\n\柁媢桾蓇?"
18 "薚泂"
19 "抻祤"
20 "瞅絒瑧謜斕..."
21 "%s 儸Бョ﹞\n\衭适嬣蓇?"
22 "諔騵瑧ス"
23 "隓恄适嬣 %s﹞\n霘黀栯麔淰柁暐⑴ḷ﹜隑悒适箹纂﹞"
24 "諔騵瑧ス"
25 "鬊Б棷蟡蘋斕..."
26 "麔淰扢鼏衭罶媢"
27 "蟡蘋斕..."
28 "覗洠鬊Б棷"
29 "薚泂"
30 "薚泂"
31 "薚泂"
32 "ョ曚骱儸伝崽柁媢桾..."
33 "薚泂"

34 "%s 攜Бョ﹞"
35 "隓恄瞅絒 %s﹞"
36 "隓恄崷殦奡襉忟﹞"
37 "眃㪫稹殦鼏衭"
38 "眃㪫稹殦"
39 "眃㪫稹殦"
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "眃㪫稹殦"
41 "儸伝崽"

42 "%s 儸Бョ﹞  衭抻鷥蓇?"
43 "隓恄抻鷥 %s﹞"
44 "隓恄唈ゥ %s﹞"
45 "隓恄唈ゥ %s﹞"


46 "覗洠鬊Б棷"
47 "%s 儸Бョ﹞\n衭适嬣蓇?"
48 "諔騵瑧ス"
49 "隓恄适嬣 %s﹞\n\霘黀栯麔淰暐⑴ḷ欄悒适箹﹞"
50 "諔騵瑧ス"
51 "隓恄唈ゥ %s﹞"
52 "諔騵瑧ス"
53 "隓恄嬣蘋 %s﹞"
54 "諔騵瑧ス"
55 "隓恄唈ゥ %s﹞"
56 "諔騵瑧ス"
57 "渿眃㪫稹殦庍ボ珜"
58 "ャ砆槉嵺屼纂咍ョ槉嵺\n\驨椲渀鞂蟺⼇柁齪А迖眃㪫稹殦﹜\n\睎薚泂衭驨椲ャ砆槉嵺蓇?"
59 "扽奡襉忟"
60 "奡襉忟攜冞﹜隓恄蟡蘋隃Б柁 .vacation.msg 麔淰﹞"
61 "諔騵瑧ス"
62 "隃Б柁 .vacation.msg 麔淰ʊ驗儸銧骱﹞"


63 "藞抻纂堈媢桾坭傶棬﹞"
64 "藞抻纂堈媢桾坭闀蕍﹞"
65 "%d 堈媢桾傶怉 %s"
66 "%d 堈媢桾傶怉 %s"
67 "%d 堈媢桾闀蕍怉 %s"
68 "%d 堈媢桾闀蕍怉 %s"
69 "槉棷儸Бョ﹞  霘渿⼓菙⺍虳磞﹞"
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/



70 "檎嬣隓恄庋踽柁瑧ス..."
71 "諔騵瑧ス"
72 "薚泂"
73 "抻祤"
74 "薚泂"

75 "薚泂"
76 "薚泂"

77 "睎纂堈儸瞅絒柁眃㪫稹殦﹜⑴逑屼泲ゝ鬊Б埏庍柁蠡晥﹞\n蒡婽楙堈媢桾渿鞂蛁灡縋楙堈儸瞅絒柁眃㪫稹殦\n柁椵稌﹞  ズ泲ゝ鬊Б埏庍柁蠡晥渿攜鞂珜楙堈媢桾柁\n纂楶ソ﹞  睎⑴髓囷え＞ⅱБ隞麔＝髓鬊Б埏庍柁蠡晥﹜ョ椵稌揧\n蛁灡髓悒﹜攜蝝埏庍柁蠡晥渿攜鞂珜楙堈眃㪫稹殦\n柁纂楶ソ﹞"
78 "暋泂瑧ス藞禋..."
79 "曚骱呥媏罐"
80 "攜衭曚骱﹜媏罐"
81 "楙堈眃㪫稹殦⑴逑屼⑴髓楸╩适銧掑柁\n\杬麟﹞  唈諞睎瑊ンッ薚泂髓悒﹜テ欹⺼楙堈眃㪫稹殦﹞  ヵ峈睎薚泂﹜霘挹＞薚泂＝“ 霘挹＞抻祤＝﹜髓抻祤欹⺼﹞"
82 "伀藺ョ囷え楙堈砆謜﹞\n睎裱衭衭忴孍泂痼魌謦汃蓇〝"
83 "諔騵瑧ス隓恄蘀抻孍泂痼魌謦汃楙堈砆謜﹞\n睎裱衭髓椔幺柁昲鳷瞅絒楙堈砆謜蓇〝"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "伝崽 %d 媢桾"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "伝崽 %d 媢桾"
86 "黀栯隞柁瑧ス..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "諔騵瑧ス - 驨椲"
88 "曚骱伝崽柁媢桾呥驨椲楙堈砆謜蓇〝"
89 "曚骱呥驨椲"
90 "砉絅呥驨椲"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "隓恄欹⺼隓淩柁棬汃﹞"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "欹⺼棬汃⼇絫〞"
93 "藞泂柁頝踛 %s 翍逑欿欹⺼﹞\n挹纂譯＞薚泂＝髓欹⺼﹜迖＞抻祤＝髓廎忒﹞"
94 "諔騵瑧ス隓恄痼魌孍泂楙堈\n砆謜﹜モ珜侇嗄ゝャ鶈﹞\n\nⅲョ渀﹜睎⑴髓藞謥⑩瞅絒楙堈砆謜\n珜椔幺昲鳷﹜迖瞅絒楙堈砆謜珜幺嬣昲鳷゛攜痼魌\n孍泂﹜(ⅲョ隓藺囷え楙堈砆謜渀﹜懼ヵ囷え)﹞"
95 "椔幺"
96 "幺嬣"


$set 5
1 "諔騵瑧ス"
2 "諔騵瑧ス"
3 "蚍婘穔婽罐媢桾\n\	    衧眃㪫稹殦斕邴汃柁埏庍渿\n\	    鞂蟺⼇﹞"
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "霘ⅲ藞抻纂堈眃㪫稹殦\n\	    隑悒藞抻＞庍ボ＝"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "媢桾斕栲咍⻏彴諟﹜\nモ珜⼓呥ゝ棤嘵怉侇嗄斕ズ儸洁柁囷え炟﹞\n霘薚泂旂匢邴柁⻏彴忔淩﹜隑悒テ箹纂﹞"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "諔騵瑧ス 柁奡襉忟攜冞﹜隓恄婽罐\n楙堈媢桾﹞\n霘廎忒怬鱗鶈え嶂冈﹜\n隑悒テ蒡纂﹞"
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "ョ蒡婽睎柁媢桾渀蠆諟僛ぇ﹞\n霘黀栯楙堈媢桾旂匢揧怉﹞  ヵ峈泲ゝ怉﹜\n迖暐睎錛衭适蒡纂﹞"
$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "霘閰箹＞蒡婽＝ョ挴泂楙堈媢桾柁稌炟欄悒﹜\n\ョ ス藺:, 棓ヾ:, 迖 Bcc: 唫⻏﹞"

$set 12
1 "眃㪫稹殦"
2 "眃㪫稹殦"
3 "displayCount"
4 "隓恄椵稌 FIFO 麔淰”%s"
5 "隓恄椵稌А蠣笱眻麔淰”%s"
6 "隓恄椵稌げ蠊”%s"
7 "隓恄椵稌棷栠笱眻麔淰”%s"
8 "隓恄椵稌 socket 麔淰”%s"


$set 13
1 "隓恄唈ゥ"
2 "隓恄嬣蘋"

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "蠹蘋眃㪫稹殦"
2 "隓恄瞅絒 %s"
3 "隓恄椵稌 FIFO 麔淰”%s"
4 "隓恄椵稌А蠣笱眻麔淰”%s"
5 "隓恄椵稌げ蠊”%s"
6 "隓恄椵稌棷栠笱眻麔淰”%s"
7 "隓恄椵稌 socket 麔淰”%s"
8 "隓恄瞅絒 %s"
9 "諔騵瑧ス - 眃㪫稹殦庍ボ"
10 "諰咭"
11 "渿眃㪫稹殦鬊Б珜"

$set 15
1 "睎儸槴泲ゝ鬊Б柁埏庍蠡晥﹞\n睎⑴髓鬊Б睎柁埏庍蠡晥﹜迖勂蛫睎柁埏庍蠡晥﹜\n迖珃ャ睎譫髱緷柁⻏殦﹞"
2 "鬊Б"
3 "勂蛫"
