$ $XConsortium: dtprintinfo.msg /main/2 1996/07/24 19:03:15 drk $
$quote "
$set DTPRINTER_SET

$ ----- These are the titles that appear on dialogs and the main window -----
ApplicationName1L  "トパ磣隉炟"
ApplicationName2L  "パ玿鞥齡汃"
$ Do not translate ApplicationName3L for this release
ApplicationName3L  "痐郖パ玿鞥"

$ ----- Common Dialog Buttons -----
YesL     "旂"
NoL      "匢"
OKL      "薚泂"
ApplyL   "伒怮鶈え"
CancelL  "抻祤"
HelpL    "赮伢諰咭"

$ ----- Find dialog -----
FindTitleL        "%s - 硻岊トパ齡汃"
MyJobNameL        "宎柁齡汃柁ボ磝"
OnlyRootJobsL     "蒟淂齡汃"
IgnoreCaseL       "芩靬淰坲"
ExactMatchL       "薚柁嗃ポ"
GotoL             "虳芼"
CancelPrintJobsL  "抻祤トパ齡汃"
PositionL         "⻏殦"
CloseL            "驨椲"
StartFindL        "絒棬硻岊"
StopFindL         "彘欐硻岊"
SearchL           "\
銌硻 %s...\n\
\n\
霘挹＞彘欐＝坭斕黫"

$ Find Information dialog messages
NoMatchesL             "隓トパ齡汃嗃ポ"

NotFoundMessageL       "\
トパ齡汃攜ョБョ﹜迖\n\
パ玿鞥揧驨椲﹞"

$ ----- Modify Show Dialog -----
ModifyShowTitleL         "%s - 埏庍䬷ざト玿"
SelectPrintersToBeShowL  "藞抻袺䬷ざ柁パ玿鞥"
SelectAllL               "ツ楶藞抻"
DeselectAllL             "抻祤ツ楶藞抻"

$ ----- Set Options Dialog -----
SetOptionsTitleL      "%s - 暋泂藞禋"
RepresentationL       "玿隃巖冈"
LargeIconL            "騰頝踛"
SmallIconL            "麵頝踛"
NameOnlyL             "蒟ボ磝"
DetailsL              "嗏樄"
ShowLabelsL           "䬷ざ簅圝"
JobsToShowL           "袺䬷ざ柁齡汃"
OnlyMineL             "蒟宎柁"
EveryoneL             "怀堈藺柁"
StatusL               "昲鳷"
ProblemFlagL          "棯纕憿簅"
InformationLineL      "媢桾ト"
UpdateIntervalL       "彶隞"
IntervalL             "渀睮睮觰(秮)"

$ ----- Print Job Properties Dialog -----
PrintJobPropsTitleL  "%s - トパ齡汃笱迒"
PrinterL             "パ玿鞥"
JobName1L            "齡汃ボ磝"
SubmittedL           "儸婽罐"
BytesL               "⻏蠣嗢"

Position1L           "⻏殦”"
JobNameL             "齡汃ボ磝”"
JobNumberL           "齡汃磍謑”"
OwnerL               "謵炟”"
DateL                "戀蛺”"
TimeL                "渀睮”"
SizeL                "騰麵”"

$ ----- Printer Properties Dialog -----
PrinterPropsTitleL    "%s - パ玿鞥笱迒"
IconLabelL            "頝踛簅圝”"
IconGroupTitleL       "頝踛”"
FindSetL              "硻岊碬ポ..."
DescriptionL          "諰咭”"
PrinterStatusL        "昲鳷”"
PrintQueueL           "パ玿鞥⻗ト”"
DeviceL               "稹殦ボ磝”"
DeviceNL              "稹殦 %d”"
UpL                   "ホ譫 - 峇棜斕"
DownL                 "ホ譯 - 廎忒峇棜"
PrinterOnServerL      "%1$s on %2$s"
DefaultDescriptionL   "楙旂 %s パ玿鞥⻗ト﹞"
$ %1 is the printer name and %2 is the server name, ex” "lp0 on warpspeed"
$ This is the value of the device field when the printer is on a remote system

$ ----- Find Set Dialog -----
FindSetTitleL       "%s - 硻岊碬ポ"
IconFoldersL        "頝踛麔淰扢”"
IconTitleL          "頝踛"
LoadingIconsL       "蟡蘋%2$d堈斕柁 %1$d堈頝踛..."
$ %1 is a counter and %2 is the total number of icons

$ ----- "Cancel" Print Job Confirmation Dialog -----
CancelTitleL     "%s - 抻祤 %s"
CancelQuestionL  "睎薚泂衭抻祤%s蓇?"

$ ----- Printer "Status" Dialog -----
PrinterStatusTitleL  "%s - パ玿鞥昲鳷"
PrinterDownL         "%sパ玿鞥廎忒峇棜﹞"
DeviceDownL          "%s稹殦廎忒峇棜﹞"

$ ----- Failed Action Dialog -----
FailedActionTitleL  "%s - %s ⼇絫"
FailedMessageL      "隓恄伒怮鶈え'%s'棬汃⺍\n\
  %s.  霘棤櫇髓譯婘モ﹞\n\n%s"

$ ----- Main Window Information Line Messages -----
GettingHelpL      "抻痤轃譫赮伢諰咭..."
SearchingL        "銌硻パ玿鞥..."
ShowingMyJobsL    "蒟䬷ざ宎柁齡汃"
PrintersHiddenL   "%d 楶パ玿鞥斕 %d楶揧騿鰳"
JobsL             "%d堈齡汃"
UpdatingActionsL  "彶隞棬汃罶涷梬..."
UpdatingL         "彶隞%s..."
$ Do not translate EditLangL for this release
EditLangL         "蹌藟卼/etc/dt/appconfig/麷伀/%s"
$ %s is the name of the printer

$ ----- Printer Menu Messages -----
PrinterMenuL         "パ玿鞥"
PrinterAcceleratorL  "P"
FindChoiceL          "硻岊..."
FindMnemonicL        "F"
FindAcceleratorL     "Ctrl+F"
ExitChoiceL          "廎忒"
ExitMnemonicL        "x"
ExitAcceleratorL     "Alt+F4"

$ ----- Selected Menu Messages -----
SelectedMenuL           "儸藞抻"
SelectedAcceleratorL    "S"

$ For Print Jobs Only - "Cancel" means to remove a print job from the printer.
$                       This choice pops up the "Cancel" Print Job Confirmation
$                       Dialog. 
CancelChoiceL           "抻祤"
CancelMnemonicL         "C"
CancelAcceleratorL      "Del"

$ For Printers Only
OpenChoiceL             "瞅絒"
OpenMnemonicL           "O"
CloseChoiceL            "驨椲"
CloseMnemonicL          "C"
HideChoiceL             "騿鰳"
HideMnemonicL           "e"
$ Do not translate RenameChoiceL for this release
RenameChoiceL           "适隞杬ボ"
$ Do not translate RenameMnemonicL for this release
RenameMnemonicL         "R"
$ Do not translate StartChoiceL for this release
StartChoiceL            "瞅沓粡睾"
$ Do not translate StartMnemonicL for this release
StartMnemonicL          "S"
$ Do not translate StopChoiceL for this release
StopChoiceL             "廎忒粡睾"
$ Do not translate StopMnemonicL for this release
StopMnemonicL           "t"
$ Do not translate EnableChoiceL for this release
EnableChoiceL           "絒棬トパ"
$ Do not translate EnableMnemonicL for this release
EnableMnemonicL         "E"
$ Do not translate DisableChoiceL for this release
DisableChoiceL          "驨椲トパ"
$ Do not translate DisableMnemonicL for this release
DisableMnemonicL        "D"

$ For Both Printers and Print Jobs
PropertiesChoiceL       "笱迒..."
PropertiesMnemonicL     "P"
PropertiesAcceleratorL  "Ctrl+Backspace"
HelpChoiceL             "赮伢諰咭"
HelpMnemonicL           "H"

$ ----- View Menu Messages -----
ViewMenuL             "黀槉"
ViewAcceleratorL      "V"
SetOptionsChoiceL     "暋泂藞禋..."
SetOptionsMnemonicL   "O"
ModifyShowChoiceL     "埏庍䬷ざト玿..."
ModifyShowMnemonicL   "M"

$ ----- Help Menu Messages -----
$ "Help" Menu uses the "HelpChoiceL" message
$ "Help" Accelerator uses the "HelpMnemonicL" message
OverviewChoiceL     "颮羏"
OverviewMnemonicL   "v"
TaskChoiceL         "齡汃"
TaskMnemonicL       "T"
ReferenceChoiceL    "棤℡罶涷"
ReferenceMnemonicL  "R"
OnItemChoiceL       "崼卼禋げ"
OnItemMnemonicL     "O"
UsingHelpChoiceL    "囷え赮伢諰咭"
UsingHelpMnemonicL  "U"
AboutChoice1L       "驨卼トパ磣隉炟"
AboutChoice2L       "驨卼トパ齡汃"
$ Do not translate AboutChoice3L for this release
AboutChoice3L       "驨卼痐郖パ玿鞥"
AboutMnemonicL      "A"

$ ----- Misc Messages -----
EmptyL            "[ 洠柁 ]"
FoundNoPrintersL  "扽岊怉パ玿鞥﹞"
NotAvailableL     "攜⑴え"
NoDefaultPrinter1L  "扽侇嗄蠡暋パ玿鞥﹞"
NoDefaultPrinter2L  "\
霘棤櫇囷え炟鰱襓諰咭儸蘀痤ヵ\n\
暋泂蠡暋パ玿鞥LPDEST蘄頨柁罶媢﹞"
$ %1 is the name of the program, and %2 is either '-edit' or '-populate'.
RootUserL "%1$s” 睎⽁禕旂淂囷え炟懼逑囷え%2$s藞禋﹞"


$ ----- Command Line Help -----
$ This message is show when the user enters 'dtprintinfo -help'
$ on the command line. The %s is a printer list generated by the program.

CommandLineHelpL "\
dtprintinfo\n\
\n\
    攜棤嘵ズ藞禋゛絒棬dtprintinfo﹜䬷ざLPDEST\n\
    パ玿鞥迖ョLPDESTゝ暋泂渀䬷ざ侇嗄蠡暋﹞\n\
\n\
dtprintinfo -p <printer>\n\
\n\
    蚍衭砫笱泂柁パ玿鞥﹜霘囷え -p 藞禋髓轡\n\
    譯トトパ⻗トボ磝欄纂”\n\
\n\
%s\
\n\
dtprintinfo -all\n\
\n\
    蚍衭砫邴パ玿鞥﹜霘囷え -all 藞禋﹞\n\
\n\
dtprintinfo -populate\n\
\n\
     -populate 藞禋蒟坯淂囷え炟囷え﹞\n\
    篎藞禋髱/etc/dt/appconfig/types/LANG\n\
斕柁邴パ玿鞥唈ゥ蠡暋パ玿鞥棬汃﹞  蚍LANGゝ泂氂﹜\n\
    棬汃鞂唈ゥョ/etc/dt/appconfig/types/C斕﹞"
