$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:50:38 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s”杬麟⺼藞禋蠆諟 \"%s\"\n\n"
2 "1386-102 \n耰蘋 %s -help 伒⑴痤怉汒謽柁諰咭﹞\n\n"

3 "1386-103 え恄”\n        %s [-options ...]\n\n\
	 藞禋讓挭”\n"
5 "1386-105    %-28s %s\n\t 篲鳷珜髓譯欄纂”\n\", \"-mode mode\", \"animation mode"

7 "1386-107 ゝ洁柁篲鳷”"
10 "1386-110 隓恄崷殦”%s\n"
11 "1386-111 崷殦 %d 堈頝踛痼蠣\n"

17 "1386-117 %s”隓恄瞅絒䬷ざ蟟 %s﹞\n"
18 "1386-118 %s”GetResource - 隓恄崷殦奡襉忟"
19 "1386-119 %s”-display 鰱禨眭冈蠆諟﹜\"%s\"\n"

20 "1386-120 -batchcount 鰱禨禕珜禨﹞"
21 "1386-121 -saturation 鰱禨⽁禕蘭卼 0.0 縋 1.0 欄睮﹞"

25 "1386-125 %s”ⅲ逑齬葰 %d 堈糬魦﹞\n"
30 "1386-130 -delay 鰱禨禕珜禨﹞"
35 "1386-135 隓恄崷殦”%s﹜髓 %s 抻鷥\n"
40 "%s”隓恄岊怉槉嵺坭鸁頝﹞囷え -create\n\
        藞禋⑴⣷ %s 唈ゥ⼓⺌儷柁槉嵺﹞\n"

