$ $XConsortium: dttypes.msg /main/2 1996/07/24 19:03:29 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"隓恄渿ズ昡ス媊沓暋泂\n"
4	"洠А⻌"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"⺌ %s蟡蘋\n"
10	"攜咭柁"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" ”\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"蠆諟 = %o, %s\n"
$ Translate "error" only
25	"え恄:  dttypes [-help]\n\tdttypes [-type filename]\n\tdttypes [-db database] [-w [rec_name regexp] [fld_name regexp]\n\t\t\t[fld_value regexp]]\n\t\t[-l [rec_name] [rec_info] [fld_name regexp] [fld_value]]\n"
$ Translate only the following” "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s 柁麷伀旂 %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"隓淩柁罶涷梬\n"
31	"攜旂淩柁鰱禨\n"
32	"隓淩柁 rec_info 唫⻏ョ  -w 藞禋斕\n"
$ do not translate "rec_info" or "-w"
33	"攜ョ -w 迖 -l 藞禋斕\n"
$ do not translate "-w" or "-l"
34	"攜咭柁藞禋\n"
35	"-help"
$ Do not Translate
36	"纂郫玿ざ冈 %s 斕蠆諟\n"

