$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.2 13 Sep 1994 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR”崷殦怉謽禨嵕ト渀僛ぇ蠆諟\n"
2 "ISTR”珜А⻌崷殦洠睮渀僛ぇ蠆諟\n"
3 "ISTR”崷殦奡襉忟渀僛ぇ蠆諟"
4 "蠡楶蠆諟"
5 "踽媝冈怐冈昋ⅰ"
6 "攜揧暐⑴"
7 "隓恄瞅絒"
