$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.2 13 Sep 1994 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "滙夼”%s ”隓恄渿麔淰ボ磝[%s]鼲葎頝踛旃\n"
2 "滙夼”%s ”ゝ挴泂麔淰ボ磝\n"
3 "蠆諟”%s”扽昡ス眃摽昡\n"
4 "怞忟襲蠆諟”%s”々嶂囥欄widget-ID 旂洠く柁\n"
5 "怞忟襲蠆諟”%s”隓恄渿衢逑玿怞忟襲\n"
6 "怞忟襲蠆諟”昡ス⽁禕淩柁ボ磝\n"
7 "怞忟襲蠆諟”%s”昡ス⽁禕 widget 嶉觕\n"
8 "蠡楶蠆諟”衶禨攜嗃ポ\n"
9 "蠆諟”objxm_comp_get_subobj - 昡スゝ xmconfigured”%s\n"
10 "麔淰扢"
11 "蝝孋蟟"
12 "耰蘋麔ボ"
13 "彶隞"
