$ +SNOTICE
$ 
$ 	$TOG: libDtMail.msg /main/4 1997/10/31 15:40:33 rafi $
$ 
$ 	RESTRICTED CONFIDENTIAL INFORMATION:
$ 	
$ 	The information in this document is subject to special
$ 	restrictions in a confidential disclosure agreement bertween
$ 	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$ 	document outside HP, IBM, Sun, USL, SCO, or Univel wihtout
$ 	Sun's specific written approval.  This documment and all copies
$ 	and derivative works thereof must be returned or destroyed at
$ 	Sun's request.
$ 
$ 	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ @(#)libDtMail.msg	1.8 03 Nov 1994
$set 1 libDtMail API set
1 ゝ僛ぇズ蠆諟﹞
2 栲堈攜怞淩 Bento 昡ス柁媢桾揧Б抻﹞
3 栲堈唈ゥ渀棯纕柁昡ス揧Б抻﹞
4 昡ス隓恄唈ゥ﹞
5 昡ス岊攜怉圊﹞
6 侇嗄奡襉忟攜冞﹜隓恄欹⺼謦汃﹞
7 禋謦汃稌怉纂堈蠆諟柁鰱禨﹞
8 睎閰箹媊沓暋泂纂堈儸媊沓暋泂蝝柁昡ス﹞
9 衭忴柁麔淰攜Бョ﹞
10 衭忴柁麔淰呥盻怞斿⑴藑籫眭冈柁瑧謜﹞
11 DtMail 攜Бョ媢桾げ蠊﹞
12 蠆諟廎擛隓淩﹞
13 楙堈圊旂纂堈蠡屼柁鬊Б﹜⽁禕ッ瞅絒懼逑幺抻﹞
14 ⅱ纂堈瑧ス嶂冈怞麔淰扢柁嬣蘋暐⑴﹞
15 栲堈 ToolTalk 媢桾隓恄搢隉﹞
16 睎柁衭忴揧謦汃ɵ峇蟟陃廕﹞
17 囷え炟斕黫禋謦汃﹞
18 栲堈昡ス隓恄Б抻﹞
19 衭忴柁麔淰隓恄唈ゥ﹞
20 欹⺼禋謦汃渀僛ぇ蠡楶蠆諟﹞
21 隃⺼昡ス呥攜齬葰睎邴衭忴柁謦汃﹞s
22 扽罶涷麷倛縋蝒婽麷倛砨嗃﹞
23 囷え炟吤黫鼲葎﹞
24 瑧ス嶂冈梬扽儸蕍汃汒炟﹞
25 挴泂柁嶂冈蕍汃攜Бョ﹞
26 挴泂柁嶂冈蕍汃隓恄欹⺼衭忴柁謦汃﹞
27 隃⺼柁嶂冈蕍汃ゝ齬葰禋謦汃﹞
28 嶂冈梬攜諝痤罶涷麷倛﹞
29 挴泂柁瑧踽⻏彴隓恄搢隉﹞
30 瑧ス蒡踽⼇絫﹞
31 MD5 麷伀奡磍縋媢桾蠡晥攜砨嗃﹞
32 淩柁欹⺼漦嗢呥盻 "mail"

$ 
$ Strings from libDtMail/Common/DtMailValuesBuiltin.C

$set 2
1 "%C" 
$ /* NL_COMMENT
$  * The %C is the time and date format, please refer to strftime man page for 
$  * explanation of each format.
$  */
