$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/3 1995/11/08 14:04:03 rswiston $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$ -------------------------------------
$ MotifApp/Application.C
$ 

$quote "

$ -------------------------------------
$ MotifApp/AskFirstCmd.C
$ 

$quote "


$set 1
1 "睎翍柁衭欹⺼楙堈杬麟蓇?"
$ -------------------------------------
$ MotifApp/DialogManager.C
$ 

$quote "


2 "薚泂"
3 "抻祤"
$ -------------------------------------
$ MotifApp/Help.C
$ 

$quote "


4 "DtMail 斿ヾ髱緷"
5 "DtMail 斿ヾ髱緷"
6 "睎⽁禕ョ鶈え嶂冈斕藞抻纂堈蠣ス﹞\n"
7 "DtMail Help"
8 "DtMail Help"


$quote "


9 "Close this folder?"
$ -------------------------------------
$ MotifApp/WarnNoUndoCmd.C
$ 

$quote "


10 "挴麟隓恄籔婘﹞羼鰹衭凭㶴蓇?"

$quote "

$set 2
1 "藞謥蠆諟﹜隓恄凭㶴\n" 
2 "囷え炟⺌⺼斕黫藞謥﹞\n" 
$ -------------------------------------
$ MotifApp/QuitCmd.C
$ 
