<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isoamsa PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isoamsa;
-->

<!ENTITY cularr   CDATA "&#8630;" ><!--ANTICLOCKWISE TOP SEMICIRCLE ARROW -->
<!ENTITY curarr   CDATA "&#8631;" ><!--CLOCKWISE TOP SEMICIRCLE ARROW -->
<!ENTITY dArr     CDATA "&#8659;" ><!--DOWNWARDS DOUBLE ARROW -->
<!ENTITY darr2    CDATA "&#8650;" ><!--DOWNWARDS PAIRED ARROWS -->
<!ENTITY dharl    CDATA "&#8643;" ><!--DOWNWARDS HARPOON WITH BARB LEFTWARDS -->
<!ENTITY dharr    CDATA "&#8642;" ><!--DOWNWARDS HARPOON WITH BARB RIGHTWARDS -->
<!ENTITY dlarr    CDATA "&#8601;" ><!--SOUTH WEST ARROW -->
<!ENTITY drarr    CDATA "&#8600;" ><!--SOUTH EAST ARROW -->
<!ENTITY hArr     CDATA "&#8660;" ><!--LEFT RIGHT DOUBLE ARROW -->
<!ENTITY harr     CDATA "&#8596;" ><!--LEFT RIGHT ARROW -->
<!ENTITY harrw    CDATA "&#8621;" ><!--LEFT RIGHT WAVE ARROW -->
<!ENTITY lAarr    CDATA "&#8666;" ><!--LEFTWARDS TRIPLE ARROW -->
<!ENTITY Larr     CDATA "&#8606;" ><!--LEFTWARDS TWO HEADED ARROW -->
<!ENTITY larr2    CDATA "&#8647;" ><!--LEFTWARDS PAIRED ARROWS -->
<!ENTITY larrhk   CDATA "&#8617;" ><!--LEFTWARDS ARROW WITH HOOK -->
<!ENTITY larrlp   CDATA "&#8619;" ><!--LEFTWARDS ARROW WITH LOOP -->
<!ENTITY larrtl   CDATA "&#8610;" ><!--LEFTWARDS ARROW WITH TAIL -->
<!ENTITY lhard    CDATA "&#8637;" ><!--LEFTWARDS HARPOON WITH BARB DOWNWARDS -->
<!ENTITY lharu    CDATA "&#8636;" ><!--LEFTWARDS HARPOON WITH BARB UPWARDS -->
<!ENTITY lrarr2   CDATA "&#8646;" ><!--LEFTWARDS ARROW OVER RIGHTWARDS ARROW -->
<!ENTITY lrhar2   CDATA "&#8651;" ><!--LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON -->
<!ENTITY lsh      CDATA "&#8624;" ><!--UPWARDS ARROW WITH TIP LEFTWARDS -->
<!ENTITY map      CDATA "&#8614;" ><!--RIGHTWARDS ARROW FROM BAR -->
<!ENTITY mumap    CDATA "&#8888;" ><!--MULTIMAP -->
<!ENTITY nearr    CDATA "&#8599;" ><!--NORTH EAST ARROW -->
<!ENTITY nhArr    CDATA "&#8654;" ><!--LEFT RIGHT DOUBLE ARROW WITH STROKE -->
<!ENTITY nharr    CDATA "&#8622;" ><!--LEFT RIGHT ARROW WITH STROKE -->
<!ENTITY nlArr    CDATA "&#8653;" ><!--LEFTWARDS DOUBLE ARROW WITH STROKE -->
<!ENTITY nlarr    CDATA "&#8602;" ><!--LEFTWARDS ARROW WITH STROKE -->
<!ENTITY nrArr    CDATA "&#8655;" ><!--RIGHTWARDS DOUBLE ARROW WITH STROKE -->
<!ENTITY nrarr    CDATA "&#8603;" ><!--RIGHTWARDS ARROW WITH STROKE -->
<!ENTITY nwarr    CDATA "&#8598;" ><!--NORTH WEST ARROW -->
<!ENTITY olarr    CDATA "&#8634;" ><!--ANTICLOCKWISE OPEN CIRCLE ARROW -->
<!ENTITY orarr    CDATA "&#8635;" ><!--CLOCKWISE OPEN CIRCLE ARROW -->
<!ENTITY rAarr    CDATA "&#8667;" ><!--RIGHTWARDS TRIPLE ARROW -->
<!ENTITY Rarr     CDATA "&#8608;" ><!--RIGHTWARDS TWO HEADED ARROW -->
<!ENTITY rarr2    CDATA "&#8649;" ><!--RIGHTWARDS PAIRED ARROWS -->
<!ENTITY rarrhk   CDATA "&#8618;" ><!--RIGHTWARDS ARROW WITH HOOK -->
<!ENTITY rarrlp   CDATA "&#8620;" ><!--RIGHTWARDS ARROW WITH LOOP -->
<!ENTITY rarrtl   CDATA "&#8611;" ><!--RIGHTWARDS ARROW WITH TAIL -->
<!ENTITY rarrw    CDATA "&#8605;" ><!--RIGHTWARDS WAVE ARROW -->
<!ENTITY rhard    CDATA "&#8641;" ><!--RIGHTWARDS HARPOON WITH BARB DOWNWARDS -->
<!ENTITY rharu    CDATA "&#8640;" ><!--RIGHTWARDS HARPOON WITH BARB UPWARDS -->
<!ENTITY rlarr2   CDATA "&#8644;" ><!--RIGHTWARDS ARROW OVER LEFTWARDS ARROW -->
<!ENTITY rlhar2   CDATA "&#8652;" ><!--RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON -->
<!ENTITY rsh      CDATA "&#8625;" ><!--UPWARDS ARROW WITH TIP RIGHTWARDS -->
<!ENTITY uArr     CDATA "&#8657;" ><!--UPWARDS DOUBLE ARROW -->
<!ENTITY uarr2    CDATA "&#8648;" ><!--UPWARDS PAIRED ARROWS -->
<!ENTITY uharl    CDATA "&#8639;" ><!--UPWARDS HARPOON WITH BARB LEFTWARDS -->
<!ENTITY uharr    CDATA "&#8638;" ><!--UPWARDS HARPOON WITH BARB RIGHTWARDS -->
<!ENTITY vArr     CDATA "&#8661;" ><!--UP DOWN DOUBLE ARROW -->
<!ENTITY varr     CDATA "&#8597;" ><!--UP DOWN ARROW -->
<!ENTITY xhArr    CDATA "&#10234;" ><!--LONG LEFT RIGHT DOUBLE ARROW -->
<!ENTITY xharr    CDATA "&#10231;" ><!--LONG LEFT RIGHT ARROW -->
<!ENTITY xlArr    CDATA "&#10232;" ><!--LONG LEFTWARDS DOUBLE ARROW -->
<!ENTITY xrArr    CDATA "&#10233;" ><!--LONG RIGHTWARDS DOUBLE ARROW -->
