<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isobox PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isobox;
-->

<!ENTITY boxDL   CDATA "&#9559;" ><!--BOX DRAWINGS DOUBLE DOWN AND LEFT -->
<!ENTITY boxDl   CDATA "&#9558;" ><!--BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE -->
<!ENTITY boxdL   CDATA "&#9557;" ><!--BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE -->
<!ENTITY boxdl   CDATA "&#9488;" ><!--BOX DRAWINGS LIGHT DOWN AND LEFT -->
<!ENTITY boxDR   CDATA "&#9556;" ><!--BOX DRAWINGS DOUBLE DOWN AND RIGHT -->
<!ENTITY boxDr   CDATA "&#9555;" ><!--BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE -->
<!ENTITY boxdR   CDATA "&#9554;" ><!--BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE -->
<!ENTITY boxdr   CDATA "&#9484;" ><!--BOX DRAWINGS LIGHT DOWN AND RIGHT -->
<!ENTITY boxH    CDATA "&#9552;" ><!--BOX DRAWINGS DOUBLE HORIZONTAL -->
<!ENTITY boxh    CDATA "&#9472;" ><!--BOX DRAWINGS LIGHT HORIZONTAL -->
<!ENTITY boxHD   CDATA "&#9574;" ><!--BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL -->
<!ENTITY boxHd   CDATA "&#9572;" ><!--BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE -->
<!ENTITY boxhD   CDATA "&#9573;" ><!--BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE -->
<!ENTITY boxhd   CDATA "&#9516;" ><!--BOX DRAWINGS LIGHT DOWN AND HORIZONTAL -->
<!ENTITY boxHU   CDATA "&#9577;" ><!--BOX DRAWINGS DOUBLE UP AND HORIZONTAL -->
<!ENTITY boxHu   CDATA "&#9575;" ><!--BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE -->
<!ENTITY boxhU   CDATA "&#9576;" ><!--BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE -->
<!ENTITY boxhu   CDATA "&#9524;" ><!--BOX DRAWINGS LIGHT UP AND HORIZONTAL -->
<!ENTITY boxUL   CDATA "&#9565;" ><!--BOX DRAWINGS DOUBLE UP AND LEFT -->
<!ENTITY boxUl   CDATA "&#9564;" ><!--BOX DRAWINGS UP DOUBLE AND LEFT SINGLE -->
<!ENTITY boxuL   CDATA "&#9563;" ><!--BOX DRAWINGS UP SINGLE AND LEFT DOUBLE -->
<!ENTITY boxul   CDATA "&#9496;" ><!--BOX DRAWINGS LIGHT UP AND LEFT -->
<!ENTITY boxUR   CDATA "&#9562;" ><!--BOX DRAWINGS DOUBLE UP AND RIGHT -->
<!ENTITY boxUr   CDATA "&#9561;" ><!--BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE -->
<!ENTITY boxuR   CDATA "&#9560;" ><!--BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE -->
<!ENTITY boxur   CDATA "&#9492;" ><!--BOX DRAWINGS LIGHT UP AND RIGHT -->
<!ENTITY boxV    CDATA "&#9553;" ><!--BOX DRAWINGS DOUBLE VERTICAL -->
<!ENTITY boxv    CDATA "&#9474;" ><!--BOX DRAWINGS LIGHT VERTICAL -->
<!ENTITY boxVH   CDATA "&#9580;" ><!--BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL -->
<!ENTITY boxVh   CDATA "&#9579;" ><!--BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE -->
<!ENTITY boxvH   CDATA "&#9578;" ><!--BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE -->
<!ENTITY boxvh   CDATA "&#9532;" ><!--BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL -->
<!ENTITY boxVL   CDATA "&#9571;" ><!--BOX DRAWINGS DOUBLE VERTICAL AND LEFT -->
<!ENTITY boxVl   CDATA "&#9570;" ><!--BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE -->
<!ENTITY boxvL   CDATA "&#9569;" ><!--BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE -->
<!ENTITY boxvl   CDATA "&#9508;" ><!--BOX DRAWINGS LIGHT VERTICAL AND LEFT -->
<!ENTITY boxVR   CDATA "&#9568;" ><!--BOX DRAWINGS DOUBLE VERTICAL AND RIGHT -->
<!ENTITY boxVr   CDATA "&#9567;" ><!--BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE -->
<!ENTITY boxvR   CDATA "&#9566;" ><!--BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE -->
<!ENTITY boxvr   CDATA "&#9500;" ><!--BOX DRAWINGS LIGHT VERTICAL AND RIGHT -->
