<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isocyr1 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isocyr1;
-->

<!ENTITY Acy      CDATA "&#1040;" ><!--CYRILLIC CAPITAL LETTER A -->
<!ENTITY acy      CDATA "&#1072;" ><!--CYRILLIC SMALL LETTER A -->
<!ENTITY Bcy      CDATA "&#1041;" ><!--CYRILLIC CAPITAL LETTER BE -->
<!ENTITY bcy      CDATA "&#1073;" ><!--CYRILLIC SMALL LETTER BE -->
<!ENTITY CHcy     CDATA "&#1063;" ><!--CYRILLIC CAPITAL LETTER CHE -->
<!ENTITY chcy     CDATA "&#1095;" ><!--CYRILLIC SMALL LETTER CHE -->
<!ENTITY Dcy      CDATA "&#1044;" ><!--CYRILLIC CAPITAL LETTER DE -->
<!ENTITY dcy      CDATA "&#1076;" ><!--CYRILLIC SMALL LETTER DE -->
<!ENTITY Ecy      CDATA "&#1069;" ><!--CYRILLIC CAPITAL LETTER E -->
<!ENTITY ecy      CDATA "&#1101;" ><!--CYRILLIC SMALL LETTER E -->
<!ENTITY Fcy      CDATA "&#1060;" ><!--CYRILLIC CAPITAL LETTER EF -->
<!ENTITY fcy      CDATA "&#1092;" ><!--CYRILLIC SMALL LETTER EF -->
<!ENTITY Gcy      CDATA "&#1043;" ><!--CYRILLIC CAPITAL LETTER GHE -->
<!ENTITY gcy      CDATA "&#1075;" ><!--CYRILLIC SMALL LETTER GHE -->
<!ENTITY HARDcy   CDATA "&#1066;" ><!--CYRILLIC CAPITAL LETTER HARD SIGN -->
<!ENTITY hardcy   CDATA "&#1098;" ><!--CYRILLIC SMALL LETTER HARD SIGN -->
<!ENTITY Icy      CDATA "&#1048;" ><!--CYRILLIC CAPITAL LETTER I -->
<!ENTITY icy      CDATA "&#1080;" ><!--CYRILLIC SMALL LETTER I -->
<!ENTITY IEcy     CDATA "&#1045;" ><!--CYRILLIC CAPITAL LETTER IE -->
<!ENTITY iecy     CDATA "&#1077;" ><!--CYRILLIC SMALL LETTER IE -->
<!ENTITY IOcy     CDATA "&#1025;" ><!--CYRILLIC CAPITAL LETTER IO -->
<!ENTITY iocy     CDATA "&#1105;" ><!--CYRILLIC SMALL LETTER IO -->
<!ENTITY Jcy      CDATA "&#1049;" ><!--CYRILLIC CAPITAL LETTER SHORT I -->
<!ENTITY jcy      CDATA "&#1081;" ><!--CYRILLIC SMALL LETTER SHORT I -->
<!ENTITY Kcy      CDATA "&#1050;" ><!--CYRILLIC CAPITAL LETTER KA -->
<!ENTITY kcy      CDATA "&#1082;" ><!--CYRILLIC SMALL LETTER KA -->
<!ENTITY KHcy     CDATA "&#1061;" ><!--CYRILLIC CAPITAL LETTER HA -->
<!ENTITY khcy     CDATA "&#1093;" ><!--CYRILLIC SMALL LETTER HA -->
<!ENTITY Lcy      CDATA "&#1051;" ><!--CYRILLIC CAPITAL LETTER EL -->
<!ENTITY lcy      CDATA "&#1083;" ><!--CYRILLIC SMALL LETTER EL -->
<!ENTITY Mcy      CDATA "&#1052;" ><!--CYRILLIC CAPITAL LETTER EM -->
<!ENTITY mcy      CDATA "&#1084;" ><!--CYRILLIC SMALL LETTER EM -->
<!ENTITY Ncy      CDATA "&#1053;" ><!--CYRILLIC CAPITAL LETTER EN -->
<!ENTITY ncy      CDATA "&#1085;" ><!--CYRILLIC SMALL LETTER EN -->
<!ENTITY numero   CDATA "&#8470;" ><!--NUMERO SIGN -->
<!ENTITY Ocy      CDATA "&#1054;" ><!--CYRILLIC CAPITAL LETTER O -->
<!ENTITY ocy      CDATA "&#1086;" ><!--CYRILLIC SMALL LETTER O -->
<!ENTITY Pcy      CDATA "&#1055;" ><!--CYRILLIC CAPITAL LETTER PE -->
<!ENTITY pcy      CDATA "&#1087;" ><!--CYRILLIC SMALL LETTER PE -->
<!ENTITY Rcy      CDATA "&#1056;" ><!--CYRILLIC CAPITAL LETTER ER -->
<!ENTITY rcy      CDATA "&#1088;" ><!--CYRILLIC SMALL LETTER ER -->
<!ENTITY Scy      CDATA "&#1057;" ><!--CYRILLIC CAPITAL LETTER ES -->
<!ENTITY scy      CDATA "&#1089;" ><!--CYRILLIC SMALL LETTER ES -->
<!ENTITY SHCHcy   CDATA "&#1065;" ><!--CYRILLIC CAPITAL LETTER SHCHA -->
<!ENTITY shchcy   CDATA "&#1097;" ><!--CYRILLIC SMALL LETTER SHCHA -->
<!ENTITY SHcy     CDATA "&#1064;" ><!--CYRILLIC CAPITAL LETTER SHA -->
<!ENTITY shcy     CDATA "&#1096;" ><!--CYRILLIC SMALL LETTER SHA -->
<!ENTITY SOFTcy   CDATA "&#1068;" ><!--CYRILLIC CAPITAL LETTER SOFT SIGN -->
<!ENTITY softcy   CDATA "&#1100;" ><!--CYRILLIC SMALL LETTER SOFT SIGN -->
<!ENTITY Tcy      CDATA "&#1058;" ><!--CYRILLIC CAPITAL LETTER TE -->
<!ENTITY tcy      CDATA "&#1090;" ><!--CYRILLIC SMALL LETTER TE -->
<!ENTITY TScy     CDATA "&#1062;" ><!--CYRILLIC CAPITAL LETTER TSE -->
<!ENTITY tscy     CDATA "&#1094;" ><!--CYRILLIC SMALL LETTER TSE -->
<!ENTITY Ucy      CDATA "&#1059;" ><!--CYRILLIC CAPITAL LETTER U -->
<!ENTITY ucy      CDATA "&#1091;" ><!--CYRILLIC SMALL LETTER U -->
<!ENTITY Vcy      CDATA "&#1042;" ><!--CYRILLIC CAPITAL LETTER VE -->
<!ENTITY vcy      CDATA "&#1074;" ><!--CYRILLIC SMALL LETTER VE -->
<!ENTITY YAcy     CDATA "&#1071;" ><!--CYRILLIC CAPITAL LETTER YA -->
<!ENTITY yacy     CDATA "&#1103;" ><!--CYRILLIC SMALL LETTER YA -->
<!ENTITY Ycy      CDATA "&#1067;" ><!--CYRILLIC CAPITAL LETTER YERU -->
<!ENTITY ycy      CDATA "&#1099;" ><!--CYRILLIC SMALL LETTER YERU -->
<!ENTITY YUcy     CDATA "&#1070;" ><!--CYRILLIC CAPITAL LETTER YU -->
<!ENTITY yucy     CDATA "&#1102;" ><!--CYRILLIC SMALL LETTER YU -->
<!ENTITY Zcy      CDATA "&#1047;" ><!--CYRILLIC CAPITAL LETTER ZE -->
<!ENTITY zcy      CDATA "&#1079;" ><!--CYRILLIC SMALL LETTER ZE -->
<!ENTITY ZHcy     CDATA "&#1046;" ><!--CYRILLIC CAPITAL LETTER ZHE -->
<!ENTITY zhcy     CDATA "&#1078;" ><!--CYRILLIC SMALL LETTER ZHE -->
