<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isogrk4 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isogrk4;
-->

<!ENTITY b.alpha    CDATA "&#120514;" ><!--MATHEMATICAL BOLD SMALL ALPHA -->
<!ENTITY b.beta     CDATA "&#120515;" ><!--MATHEMATICAL BOLD SMALL BETA -->
<!ENTITY b.chi      CDATA "&#120536;" ><!--MATHEMATICAL BOLD SMALL CHI -->
<!ENTITY b.Delta    CDATA "&#120491;" ><!--MATHEMATICAL BOLD CAPITAL DELTA -->
<!ENTITY b.delta    CDATA "&#120517;" ><!--MATHEMATICAL BOLD SMALL DELTA -->
<!ENTITY b.epsi     CDATA "&#120518;" ><!--MATHEMATICAL BOLD SMALL EPSILON -->
<!ENTITY b.epsiv    CDATA "&#120540;" ><!--MATHEMATICAL BOLD EPSILON SYMBOL -->
<!ENTITY b.eta      CDATA "&#120520;" ><!--MATHEMATICAL BOLD SMALL ETA -->
<!ENTITY b.Gamma    CDATA "&#120490;" ><!--MATHEMATICAL BOLD CAPITAL GAMMA -->
<!ENTITY b.gamma    CDATA "&#120516;" ><!--MATHEMATICAL BOLD SMALL GAMMA -->
<!ENTITY b.Gammad   CDATA "&#988;" ><!--GREEK LETTER DIGAMMA -->
<!ENTITY b.gammad   CDATA "&#989;" ><!--GREEK SMALL LETTER DIGAMMA -->
<!ENTITY b.iota     CDATA "&#120522;" ><!--MATHEMATICAL BOLD SMALL IOTA -->
<!ENTITY b.kappa    CDATA "&#120523;" ><!--MATHEMATICAL BOLD SMALL KAPPA -->
<!ENTITY b.kappav   CDATA "&#120542;" ><!--MATHEMATICAL BOLD KAPPA SYMBOL -->
<!ENTITY b.Lambda   CDATA "&#120498;" ><!--MATHEMATICAL BOLD CAPITAL LAMDA -->
<!ENTITY b.lambda   CDATA "&#120524;" ><!--MATHEMATICAL BOLD SMALL LAMDA -->
<!ENTITY b.mu       CDATA "&#120525;" ><!--MATHEMATICAL BOLD SMALL MU -->
<!ENTITY b.nu       CDATA "&#120526;" ><!--MATHEMATICAL BOLD SMALL NU -->
<!ENTITY b.Omega    CDATA "&#120512;" ><!--MATHEMATICAL BOLD CAPITAL OMEGA -->
<!ENTITY b.omega    CDATA "&#120538;" ><!--MATHEMATICAL BOLD SMALL OMEGA -->
<!ENTITY b.Phi      CDATA "&#120509;" ><!--MATHEMATICAL BOLD CAPITAL PHI -->
<!ENTITY b.phi      CDATA "&#120535;" ><!--MATHEMATICAL BOLD SMALL PHI -->
<!ENTITY b.phiv     CDATA "&#120543;" ><!--MATHEMATICAL BOLD PHI SYMBOL -->
<!ENTITY b.Pi       CDATA "&#120503;" ><!--MATHEMATICAL BOLD CAPITAL PI -->
<!ENTITY b.pi       CDATA "&#120529;" ><!--MATHEMATICAL BOLD SMALL PI -->
<!ENTITY b.piv      CDATA "&#120545;" ><!--MATHEMATICAL BOLD PI SYMBOL -->
<!ENTITY b.Psi      CDATA "&#120511;" ><!--MATHEMATICAL BOLD CAPITAL PSI -->
<!ENTITY b.psi      CDATA "&#120537;" ><!--MATHEMATICAL BOLD SMALL PSI -->
<!ENTITY b.rho      CDATA "&#120530;" ><!--MATHEMATICAL BOLD SMALL RHO -->
<!ENTITY b.rhov     CDATA "&#120544;" ><!--MATHEMATICAL BOLD RHO SYMBOL -->
<!ENTITY b.Sigma    CDATA "&#120506;" ><!--MATHEMATICAL BOLD CAPITAL SIGMA -->
<!ENTITY b.sigma    CDATA "&#120532;" ><!--MATHEMATICAL BOLD SMALL SIGMA -->
<!ENTITY b.sigmav   CDATA "&#120531;" ><!--MATHEMATICAL BOLD SMALL FINAL SIGMA -->
<!ENTITY b.tau      CDATA "&#120533;" ><!--MATHEMATICAL BOLD SMALL TAU -->
<!ENTITY b.Theta    CDATA "&#120495;" ><!--MATHEMATICAL BOLD CAPITAL THETA -->
<!ENTITY b.thetas   CDATA "&#120521;" ><!--MATHEMATICAL BOLD SMALL THETA -->
<!ENTITY b.thetav   CDATA "&#120541;" ><!--MATHEMATICAL BOLD THETA SYMBOL -->
<!ENTITY b.Upsi     CDATA "&#120508;" ><!--MATHEMATICAL BOLD CAPITAL UPSILON -->
<!ENTITY b.upsi     CDATA "&#120534;" ><!--MATHEMATICAL BOLD SMALL UPSILON -->
<!ENTITY b.Xi       CDATA "&#120501;" ><!--MATHEMATICAL BOLD CAPITAL XI -->
<!ENTITY b.xi       CDATA "&#120527;" ><!--MATHEMATICAL BOLD SMALL XI -->
<!ENTITY b.zeta     CDATA "&#120519;" ><!--MATHEMATICAL BOLD SMALL ZETA -->
