<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isogrk1 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isogrk1;
-->

<!ENTITY Agr    CDATA "&#913;" ><!--GREEK CAPITAL LETTER ALPHA -->
<!ENTITY agr    CDATA "&#945;" ><!--GREEK SMALL LETTER ALPHA -->
<!ENTITY Bgr    CDATA "&#914;" ><!--GREEK CAPITAL LETTER BETA -->
<!ENTITY bgr    CDATA "&#946;" ><!--GREEK SMALL LETTER BETA -->
<!ENTITY Dgr    CDATA "&#916;" ><!--GREEK CAPITAL LETTER DELTA -->
<!ENTITY dgr    CDATA "&#948;" ><!--GREEK SMALL LETTER DELTA -->
<!ENTITY EEgr   CDATA "&#919;" ><!--GREEK CAPITAL LETTER ETA -->
<!ENTITY eegr   CDATA "&#951;" ><!--GREEK SMALL LETTER ETA -->
<!ENTITY Egr    CDATA "&#917;" ><!--GREEK CAPITAL LETTER EPSILON -->
<!ENTITY egr    CDATA "&#949;" ><!--GREEK SMALL LETTER EPSILON -->
<!ENTITY Ggr    CDATA "&#915;" ><!--GREEK CAPITAL LETTER GAMMA -->
<!ENTITY ggr    CDATA "&#947;" ><!--GREEK SMALL LETTER GAMMA -->
<!ENTITY Igr    CDATA "&#921;" ><!--GREEK CAPITAL LETTER IOTA -->
<!ENTITY igr    CDATA "&#953;" ><!--GREEK SMALL LETTER IOTA -->
<!ENTITY Kgr    CDATA "&#922;" ><!--GREEK CAPITAL LETTER KAPPA -->
<!ENTITY kgr    CDATA "&#954;" ><!--GREEK SMALL LETTER KAPPA -->
<!ENTITY KHgr   CDATA "&#935;" ><!--GREEK CAPITAL LETTER CHI -->
<!ENTITY khgr   CDATA "&#967;" ><!--GREEK SMALL LETTER CHI -->
<!ENTITY Lgr    CDATA "&#923;" ><!--GREEK CAPITAL LETTER LAMDA -->
<!ENTITY lgr    CDATA "&#955;" ><!--GREEK SMALL LETTER LAMDA -->
<!ENTITY Mgr    CDATA "&#924;" ><!--GREEK CAPITAL LETTER MU -->
<!ENTITY mgr    CDATA "&#956;" ><!--GREEK SMALL LETTER MU -->
<!ENTITY Ngr    CDATA "&#925;" ><!--GREEK CAPITAL LETTER NU -->
<!ENTITY ngr    CDATA "&#957;" ><!--GREEK SMALL LETTER NU -->
<!ENTITY Ogr    CDATA "&#927;" ><!--GREEK CAPITAL LETTER OMICRON -->
<!ENTITY ogr    CDATA "&#959;" ><!--GREEK SMALL LETTER OMICRON -->
<!ENTITY OHgr   CDATA "&#937;" ><!--GREEK CAPITAL LETTER OMEGA -->
<!ENTITY ohgr   CDATA "&#969;" ><!--GREEK SMALL LETTER OMEGA -->
<!ENTITY Pgr    CDATA "&#928;" ><!--GREEK CAPITAL LETTER PI -->
<!ENTITY pgr    CDATA "&#960;" ><!--GREEK SMALL LETTER PI -->
<!ENTITY PHgr   CDATA "&#934;" ><!--GREEK CAPITAL LETTER PHI -->
<!ENTITY phgr   CDATA "&#966;" ><!--GREEK SMALL LETTER PHI -->
<!ENTITY PSgr   CDATA "&#936;" ><!--GREEK CAPITAL LETTER PSI -->
<!ENTITY psgr   CDATA "&#968;" ><!--GREEK SMALL LETTER PSI -->
<!ENTITY Rgr    CDATA "&#929;" ><!--GREEK CAPITAL LETTER RHO -->
<!ENTITY rgr    CDATA "&#961;" ><!--GREEK SMALL LETTER RHO -->
<!ENTITY sfgr   CDATA "&#962;" ><!--GREEK SMALL LETTER FINAL SIGMA -->
<!ENTITY Sgr    CDATA "&#931;" ><!--GREEK CAPITAL LETTER SIGMA -->
<!ENTITY sgr    CDATA "&#963;" ><!--GREEK SMALL LETTER SIGMA -->
<!ENTITY Tgr    CDATA "&#932;" ><!--GREEK CAPITAL LETTER TAU -->
<!ENTITY tgr    CDATA "&#964;" ><!--GREEK SMALL LETTER TAU -->
<!ENTITY THgr   CDATA "&#920;" ><!--GREEK CAPITAL LETTER THETA -->
<!ENTITY thgr   CDATA "&#952;" ><!--GREEK SMALL LETTER THETA -->
<!ENTITY Ugr    CDATA "&#933;" ><!--GREEK CAPITAL LETTER UPSILON -->
<!ENTITY ugr    CDATA "&#965;" ><!--GREEK SMALL LETTER UPSILON -->
<!ENTITY Xgr    CDATA "&#926;" ><!--GREEK CAPITAL LETTER XI -->
<!ENTITY xgr    CDATA "&#958;" ><!--GREEK SMALL LETTER XI -->
<!ENTITY Zgr    CDATA "&#918;" ><!--GREEK CAPITAL LETTER ZETA -->
<!ENTITY zgr    CDATA "&#950;" ><!--GREEK SMALL LETTER ZETA -->
