<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isolat1 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isolat1;
-->

<!ENTITY Aacute   CDATA "&#193;" ><!--LATIN CAPITAL LETTER A WITH ACUTE -->
<!ENTITY aacute   CDATA "&#225;" ><!--LATIN SMALL LETTER A WITH ACUTE -->
<!ENTITY Acirc    CDATA "&#194;" ><!--LATIN CAPITAL LETTER A WITH CIRCUMFLEX -->
<!ENTITY acirc    CDATA "&#226;" ><!--LATIN SMALL LETTER A WITH CIRCUMFLEX -->
<!ENTITY AElig    CDATA "&#198;" ><!--LATIN CAPITAL LETTER AE -->
<!ENTITY aelig    CDATA "&#230;" ><!--LATIN SMALL LETTER AE -->
<!ENTITY Agrave   CDATA "&#192;" ><!--LATIN CAPITAL LETTER A WITH GRAVE -->
<!ENTITY agrave   CDATA "&#224;" ><!--LATIN SMALL LETTER A WITH GRAVE -->
<!ENTITY Aring    CDATA "&#197;" ><!--LATIN CAPITAL LETTER A WITH RING ABOVE -->
<!ENTITY aring    CDATA "&#229;" ><!--LATIN SMALL LETTER A WITH RING ABOVE -->
<!ENTITY Atilde   CDATA "&#195;" ><!--LATIN CAPITAL LETTER A WITH TILDE -->
<!ENTITY atilde   CDATA "&#227;" ><!--LATIN SMALL LETTER A WITH TILDE -->
<!ENTITY Auml     CDATA "&#196;" ><!--LATIN CAPITAL LETTER A WITH DIAERESIS -->
<!ENTITY auml     CDATA "&#228;" ><!--LATIN SMALL LETTER A WITH DIAERESIS -->
<!ENTITY Ccedil   CDATA "&#199;" ><!--LATIN CAPITAL LETTER C WITH CEDILLA -->
<!ENTITY ccedil   CDATA "&#231;" ><!--LATIN SMALL LETTER C WITH CEDILLA -->
<!ENTITY Eacute   CDATA "&#201;" ><!--LATIN CAPITAL LETTER E WITH ACUTE -->
<!ENTITY eacute   CDATA "&#233;" ><!--LATIN SMALL LETTER E WITH ACUTE -->
<!ENTITY Ecirc    CDATA "&#202;" ><!--LATIN CAPITAL LETTER E WITH CIRCUMFLEX -->
<!ENTITY ecirc    CDATA "&#234;" ><!--LATIN SMALL LETTER E WITH CIRCUMFLEX -->
<!ENTITY Egrave   CDATA "&#200;" ><!--LATIN CAPITAL LETTER E WITH GRAVE -->
<!ENTITY egrave   CDATA "&#232;" ><!--LATIN SMALL LETTER E WITH GRAVE -->
<!ENTITY ETH      CDATA "&#208;" ><!--LATIN CAPITAL LETTER ETH -->
<!ENTITY eth      CDATA "&#240;" ><!--LATIN SMALL LETTER ETH -->
<!ENTITY Euml     CDATA "&#203;" ><!--LATIN CAPITAL LETTER E WITH DIAERESIS -->
<!ENTITY euml     CDATA "&#235;" ><!--LATIN SMALL LETTER E WITH DIAERESIS -->
<!ENTITY Iacute   CDATA "&#205;" ><!--LATIN CAPITAL LETTER I WITH ACUTE -->
<!ENTITY iacute   CDATA "&#237;" ><!--LATIN SMALL LETTER I WITH ACUTE -->
<!ENTITY Icirc    CDATA "&#206;" ><!--LATIN CAPITAL LETTER I WITH CIRCUMFLEX -->
<!ENTITY icirc    CDATA "&#238;" ><!--LATIN SMALL LETTER I WITH CIRCUMFLEX -->
<!ENTITY Igrave   CDATA "&#204;" ><!--LATIN CAPITAL LETTER I WITH GRAVE -->
<!ENTITY igrave   CDATA "&#236;" ><!--LATIN SMALL LETTER I WITH GRAVE -->
<!ENTITY Iuml     CDATA "&#207;" ><!--LATIN CAPITAL LETTER I WITH DIAERESIS -->
<!ENTITY iuml     CDATA "&#239;" ><!--LATIN SMALL LETTER I WITH DIAERESIS -->
<!ENTITY Ntilde   CDATA "&#209;" ><!--LATIN CAPITAL LETTER N WITH TILDE -->
<!ENTITY ntilde   CDATA "&#241;" ><!--LATIN SMALL LETTER N WITH TILDE -->
<!ENTITY Oacute   CDATA "&#211;" ><!--LATIN CAPITAL LETTER O WITH ACUTE -->
<!ENTITY oacute   CDATA "&#243;" ><!--LATIN SMALL LETTER O WITH ACUTE -->
<!ENTITY Ocirc    CDATA "&#212;" ><!--LATIN CAPITAL LETTER O WITH CIRCUMFLEX -->
<!ENTITY ocirc    CDATA "&#244;" ><!--LATIN SMALL LETTER O WITH CIRCUMFLEX -->
<!ENTITY Ograve   CDATA "&#210;" ><!--LATIN CAPITAL LETTER O WITH GRAVE -->
<!ENTITY ograve   CDATA "&#242;" ><!--LATIN SMALL LETTER O WITH GRAVE -->
<!ENTITY Oslash   CDATA "&#216;" ><!--LATIN CAPITAL LETTER O WITH STROKE -->
<!ENTITY oslash   CDATA "&#248;" ><!--LATIN SMALL LETTER O WITH STROKE -->
<!ENTITY Otilde   CDATA "&#213;" ><!--LATIN CAPITAL LETTER O WITH TILDE -->
<!ENTITY otilde   CDATA "&#245;" ><!--LATIN SMALL LETTER O WITH TILDE -->
<!ENTITY Ouml     CDATA "&#214;" ><!--LATIN CAPITAL LETTER O WITH DIAERESIS -->
<!ENTITY ouml     CDATA "&#246;" ><!--LATIN SMALL LETTER O WITH DIAERESIS -->
<!ENTITY szlig    CDATA "&#223;" ><!--LATIN SMALL LETTER SHARP S -->
<!ENTITY THORN    CDATA "&#222;" ><!--LATIN CAPITAL LETTER THORN -->
<!ENTITY thorn    CDATA "&#254;" ><!--LATIN SMALL LETTER THORN -->
<!ENTITY Uacute   CDATA "&#218;" ><!--LATIN CAPITAL LETTER U WITH ACUTE -->
<!ENTITY uacute   CDATA "&#250;" ><!--LATIN SMALL LETTER U WITH ACUTE -->
<!ENTITY Ucirc    CDATA "&#219;" ><!--LATIN CAPITAL LETTER U WITH CIRCUMFLEX -->
<!ENTITY ucirc    CDATA "&#251;" ><!--LATIN SMALL LETTER U WITH CIRCUMFLEX -->
<!ENTITY Ugrave   CDATA "&#217;" ><!--LATIN CAPITAL LETTER U WITH GRAVE -->
<!ENTITY ugrave   CDATA "&#249;" ><!--LATIN SMALL LETTER U WITH GRAVE -->
<!ENTITY Uuml     CDATA "&#220;" ><!--LATIN CAPITAL LETTER U WITH DIAERESIS -->
<!ENTITY uuml     CDATA "&#252;" ><!--LATIN SMALL LETTER U WITH DIAERESIS -->
<!ENTITY Yacute   CDATA "&#221;" ><!--LATIN CAPITAL LETTER Y WITH ACUTE -->
<!ENTITY yacute   CDATA "&#253;" ><!--LATIN SMALL LETTER Y WITH ACUTE -->
<!ENTITY yuml     CDATA "&#255;" ><!--LATIN SMALL LETTER Y WITH DIAERESIS -->
