<!--
     (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!--
     Character entity set. Typical invocation:
     <!ENTITY % isolat2 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN">
     %isolat2;
-->

<!ENTITY Abreve   CDATA "&#258;" ><!--LATIN CAPITAL LETTER A WITH BREVE -->
<!ENTITY abreve   CDATA "&#259;" ><!--LATIN SMALL LETTER A WITH BREVE -->
<!ENTITY Amacr    CDATA "&#256;" ><!--LATIN CAPITAL LETTER A WITH MACRON -->
<!ENTITY amacr    CDATA "&#257;" ><!--LATIN SMALL LETTER A WITH MACRON -->
<!ENTITY Aogon    CDATA "&#260;" ><!--LATIN CAPITAL LETTER A WITH OGONEK -->
<!ENTITY aogon    CDATA "&#261;" ><!--LATIN SMALL LETTER A WITH OGONEK -->
<!ENTITY Cacute   CDATA "&#262;" ><!--LATIN CAPITAL LETTER C WITH ACUTE -->
<!ENTITY cacute   CDATA "&#263;" ><!--LATIN SMALL LETTER C WITH ACUTE -->
<!ENTITY Ccaron   CDATA "&#268;" ><!--LATIN CAPITAL LETTER C WITH CARON -->
<!ENTITY ccaron   CDATA "&#269;" ><!--LATIN SMALL LETTER C WITH CARON -->
<!ENTITY Ccirc    CDATA "&#264;" ><!--LATIN CAPITAL LETTER C WITH CIRCUMFLEX -->
<!ENTITY ccirc    CDATA "&#265;" ><!--LATIN SMALL LETTER C WITH CIRCUMFLEX -->
<!ENTITY Cdot     CDATA "&#266;" ><!--LATIN CAPITAL LETTER C WITH DOT ABOVE -->
<!ENTITY cdot     CDATA "&#267;" ><!--LATIN SMALL LETTER C WITH DOT ABOVE -->
<!ENTITY Dcaron   CDATA "&#270;" ><!--LATIN CAPITAL LETTER D WITH CARON -->
<!ENTITY dcaron   CDATA "&#271;" ><!--LATIN SMALL LETTER D WITH CARON -->
<!ENTITY Dstrok   CDATA "&#272;" ><!--LATIN CAPITAL LETTER D WITH STROKE -->
<!ENTITY dstrok   CDATA "&#273;" ><!--LATIN SMALL LETTER D WITH STROKE -->
<!ENTITY Ecaron   CDATA "&#282;" ><!--LATIN CAPITAL LETTER E WITH CARON -->
<!ENTITY ecaron   CDATA "&#283;" ><!--LATIN SMALL LETTER E WITH CARON -->
<!ENTITY Edot     CDATA "&#278;" ><!--LATIN CAPITAL LETTER E WITH DOT ABOVE -->
<!ENTITY edot     CDATA "&#279;" ><!--LATIN SMALL LETTER E WITH DOT ABOVE -->
<!ENTITY Emacr    CDATA "&#274;" ><!--LATIN CAPITAL LETTER E WITH MACRON -->
<!ENTITY emacr    CDATA "&#275;" ><!--LATIN SMALL LETTER E WITH MACRON -->
<!ENTITY ENG      CDATA "&#330;" ><!--LATIN CAPITAL LETTER ENG -->
<!ENTITY eng      CDATA "&#331;" ><!--LATIN SMALL LETTER ENG -->
<!ENTITY Eogon    CDATA "&#280;" ><!--LATIN CAPITAL LETTER E WITH OGONEK -->
<!ENTITY eogon    CDATA "&#281;" ><!--LATIN SMALL LETTER E WITH OGONEK -->
<!ENTITY gacute   CDATA "&#501;" ><!--LATIN SMALL LETTER G WITH ACUTE -->
<!ENTITY Gbreve   CDATA "&#286;" ><!--LATIN CAPITAL LETTER G WITH BREVE -->
<!ENTITY gbreve   CDATA "&#287;" ><!--LATIN SMALL LETTER G WITH BREVE -->
<!ENTITY Gcedil   CDATA "&#290;" ><!--LATIN CAPITAL LETTER G WITH CEDILLA -->
<!ENTITY Gcirc    CDATA "&#284;" ><!--LATIN CAPITAL LETTER G WITH CIRCUMFLEX -->
<!ENTITY gcirc    CDATA "&#285;" ><!--LATIN SMALL LETTER G WITH CIRCUMFLEX -->
<!ENTITY Gdot     CDATA "&#288;" ><!--LATIN CAPITAL LETTER G WITH DOT ABOVE -->
<!ENTITY gdot     CDATA "&#289;" ><!--LATIN SMALL LETTER G WITH DOT ABOVE -->
<!ENTITY Hcirc    CDATA "&#292;" ><!--LATIN CAPITAL LETTER H WITH CIRCUMFLEX -->
<!ENTITY hcirc    CDATA "&#293;" ><!--LATIN SMALL LETTER H WITH CIRCUMFLEX -->
<!ENTITY Hstrok   CDATA "&#294;" ><!--LATIN CAPITAL LETTER H WITH STROKE -->
<!ENTITY hstrok   CDATA "&#295;" ><!--LATIN SMALL LETTER H WITH STROKE -->
<!ENTITY Idot     CDATA "&#304;" ><!--LATIN CAPITAL LETTER I WITH DOT ABOVE -->
<!ENTITY IJlig    CDATA "&#306;" ><!--LATIN CAPITAL LIGATURE IJ -->
<!ENTITY ijlig    CDATA "&#307;" ><!--LATIN SMALL LIGATURE IJ -->
<!ENTITY Imacr    CDATA "&#298;" ><!--LATIN CAPITAL LETTER I WITH MACRON -->
<!ENTITY imacr    CDATA "&#299;" ><!--LATIN SMALL LETTER I WITH MACRON -->
<!ENTITY inodot   CDATA "&#305;" ><!--LATIN SMALL LETTER DOTLESS I -->
<!ENTITY Iogon    CDATA "&#302;" ><!--LATIN CAPITAL LETTER I WITH OGONEK -->
<!ENTITY iogon    CDATA "&#303;" ><!--LATIN SMALL LETTER I WITH OGONEK -->
<!ENTITY Itilde   CDATA "&#296;" ><!--LATIN CAPITAL LETTER I WITH TILDE -->
<!ENTITY itilde   CDATA "&#297;" ><!--LATIN SMALL LETTER I WITH TILDE -->
<!ENTITY Jcirc    CDATA "&#308;" ><!--LATIN CAPITAL LETTER J WITH CIRCUMFLEX -->
<!ENTITY jcirc    CDATA "&#309;" ><!--LATIN SMALL LETTER J WITH CIRCUMFLEX -->
<!ENTITY Kcedil   CDATA "&#310;" ><!--LATIN CAPITAL LETTER K WITH CEDILLA -->
<!ENTITY kcedil   CDATA "&#311;" ><!--LATIN SMALL LETTER K WITH CEDILLA -->
<!ENTITY kgreen   CDATA "&#312;" ><!--LATIN SMALL LETTER KRA -->
<!ENTITY Lacute   CDATA "&#313;" ><!--LATIN CAPITAL LETTER L WITH ACUTE -->
<!ENTITY lacute   CDATA "&#314;" ><!--LATIN SMALL LETTER L WITH ACUTE -->
<!ENTITY Lcaron   CDATA "&#317;" ><!--LATIN CAPITAL LETTER L WITH CARON -->
<!ENTITY lcaron   CDATA "&#318;" ><!--LATIN SMALL LETTER L WITH CARON -->
<!ENTITY Lcedil   CDATA "&#315;" ><!--LATIN CAPITAL LETTER L WITH CEDILLA -->
<!ENTITY lcedil   CDATA "&#316;" ><!--LATIN SMALL LETTER L WITH CEDILLA -->
<!ENTITY Lmidot   CDATA "&#319;" ><!--LATIN CAPITAL LETTER L WITH MIDDLE DOT -->
<!ENTITY lmidot   CDATA "&#320;" ><!--LATIN SMALL LETTER L WITH MIDDLE DOT -->
<!ENTITY Lstrok   CDATA "&#321;" ><!--LATIN CAPITAL LETTER L WITH STROKE -->
<!ENTITY lstrok   CDATA "&#322;" ><!--LATIN SMALL LETTER L WITH STROKE -->
<!ENTITY Nacute   CDATA "&#323;" ><!--LATIN CAPITAL LETTER N WITH ACUTE -->
<!ENTITY nacute   CDATA "&#324;" ><!--LATIN SMALL LETTER N WITH ACUTE -->
<!ENTITY napos    CDATA "&#329;" ><!--LATIN SMALL LETTER N PRECEDED BY APOSTROPHE -->
<!ENTITY Ncaron   CDATA "&#327;" ><!--LATIN CAPITAL LETTER N WITH CARON -->
<!ENTITY ncaron   CDATA "&#328;" ><!--LATIN SMALL LETTER N WITH CARON -->
<!ENTITY Ncedil   CDATA "&#325;" ><!--LATIN CAPITAL LETTER N WITH CEDILLA -->
<!ENTITY ncedil   CDATA "&#326;" ><!--LATIN SMALL LETTER N WITH CEDILLA -->
<!ENTITY Odblac   CDATA "&#336;" ><!--LATIN CAPITAL LETTER O WITH DOUBLE ACUTE -->
<!ENTITY odblac   CDATA "&#337;" ><!--LATIN SMALL LETTER O WITH DOUBLE ACUTE -->
<!ENTITY OElig    CDATA "&#338;" ><!--LATIN CAPITAL LIGATURE OE -->
<!ENTITY oelig    CDATA "&#339;" ><!--LATIN SMALL LIGATURE OE -->
<!ENTITY Omacr    CDATA "&#332;" ><!--LATIN CAPITAL LETTER O WITH MACRON -->
<!ENTITY omacr    CDATA "&#333;" ><!--LATIN SMALL LETTER O WITH MACRON -->
<!ENTITY Racute   CDATA "&#340;" ><!--LATIN CAPITAL LETTER R WITH ACUTE -->
<!ENTITY racute   CDATA "&#341;" ><!--LATIN SMALL LETTER R WITH ACUTE -->
<!ENTITY Rcaron   CDATA "&#344;" ><!--LATIN CAPITAL LETTER R WITH CARON -->
<!ENTITY rcaron   CDATA "&#345;" ><!--LATIN SMALL LETTER R WITH CARON -->
<!ENTITY Rcedil   CDATA "&#342;" ><!--LATIN CAPITAL LETTER R WITH CEDILLA -->
<!ENTITY rcedil   CDATA "&#343;" ><!--LATIN SMALL LETTER R WITH CEDILLA -->
<!ENTITY Sacute   CDATA "&#346;" ><!--LATIN CAPITAL LETTER S WITH ACUTE -->
<!ENTITY sacute   CDATA "&#347;" ><!--LATIN SMALL LETTER S WITH ACUTE -->
<!ENTITY Scaron   CDATA "&#352;" ><!--LATIN CAPITAL LETTER S WITH CARON -->
<!ENTITY scaron   CDATA "&#353;" ><!--LATIN SMALL LETTER S WITH CARON -->
<!ENTITY Scedil   CDATA "&#350;" ><!--LATIN CAPITAL LETTER S WITH CEDILLA -->
<!ENTITY scedil   CDATA "&#351;" ><!--LATIN SMALL LETTER S WITH CEDILLA -->
<!ENTITY Scirc    CDATA "&#348;" ><!--LATIN CAPITAL LETTER S WITH CIRCUMFLEX -->
<!ENTITY scirc    CDATA "&#349;" ><!--LATIN SMALL LETTER S WITH CIRCUMFLEX -->
<!ENTITY Tcaron   CDATA "&#356;" ><!--LATIN CAPITAL LETTER T WITH CARON -->
<!ENTITY tcaron   CDATA "&#357;" ><!--LATIN SMALL LETTER T WITH CARON -->
<!ENTITY Tcedil   CDATA "&#354;" ><!--LATIN CAPITAL LETTER T WITH CEDILLA -->
<!ENTITY tcedil   CDATA "&#355;" ><!--LATIN SMALL LETTER T WITH CEDILLA -->
<!ENTITY Tstrok   CDATA "&#358;" ><!--LATIN CAPITAL LETTER T WITH STROKE -->
<!ENTITY tstrok   CDATA "&#359;" ><!--LATIN SMALL LETTER T WITH STROKE -->
<!ENTITY Ubreve   CDATA "&#364;" ><!--LATIN CAPITAL LETTER U WITH BREVE -->
<!ENTITY ubreve   CDATA "&#365;" ><!--LATIN SMALL LETTER U WITH BREVE -->
<!ENTITY Udblac   CDATA "&#368;" ><!--LATIN CAPITAL LETTER U WITH DOUBLE ACUTE -->
<!ENTITY udblac   CDATA "&#369;" ><!--LATIN SMALL LETTER U WITH DOUBLE ACUTE -->
<!ENTITY Umacr    CDATA "&#362;" ><!--LATIN CAPITAL LETTER U WITH MACRON -->
<!ENTITY umacr    CDATA "&#363;" ><!--LATIN SMALL LETTER U WITH MACRON -->
<!ENTITY Uogon    CDATA "&#370;" ><!--LATIN CAPITAL LETTER U WITH OGONEK -->
<!ENTITY uogon    CDATA "&#371;" ><!--LATIN SMALL LETTER U WITH OGONEK -->
<!ENTITY Uring    CDATA "&#366;" ><!--LATIN CAPITAL LETTER U WITH RING ABOVE -->
<!ENTITY uring    CDATA "&#367;" ><!--LATIN SMALL LETTER U WITH RING ABOVE -->
<!ENTITY Utilde   CDATA "&#360;" ><!--LATIN CAPITAL LETTER U WITH TILDE -->
<!ENTITY utilde   CDATA "&#361;" ><!--LATIN SMALL LETTER U WITH TILDE -->
<!ENTITY Wcirc    CDATA "&#372;" ><!--LATIN CAPITAL LETTER W WITH CIRCUMFLEX -->
<!ENTITY wcirc    CDATA "&#373;" ><!--LATIN SMALL LETTER W WITH CIRCUMFLEX -->
<!ENTITY Ycirc    CDATA "&#374;" ><!--LATIN CAPITAL LETTER Y WITH CIRCUMFLEX -->
<!ENTITY ycirc    CDATA "&#375;" ><!--LATIN SMALL LETTER Y WITH CIRCUMFLEX -->
<!ENTITY Yuml     CDATA "&#376;" ><!--LATIN CAPITAL LETTER Y WITH DIAERESIS -->
<!ENTITY Zacute   CDATA "&#377;" ><!--LATIN CAPITAL LETTER Z WITH ACUTE -->
<!ENTITY zacute   CDATA "&#378;" ><!--LATIN SMALL LETTER Z WITH ACUTE -->
<!ENTITY Zcaron   CDATA "&#381;" ><!--LATIN CAPITAL LETTER Z WITH CARON -->
<!ENTITY zcaron   CDATA "&#382;" ><!--LATIN SMALL LETTER Z WITH CARON -->
<!ENTITY Zdot     CDATA "&#379;" ><!--LATIN CAPITAL LETTER Z WITH DOT ABOVE -->
<!ENTITY zdot     CDATA "&#380;" ><!--LATIN SMALL LETTER Z WITH DOT ABOVE -->
